In [2]:
import pandas as pd
import yfinance as yf
import os

In [6]:
# Usando arquivo CSV com lista de empresas baixado do site da B3 #

listacsv = pd.read_csv('acoeslistadasb3_26062025.csv')
empresas = []
#listacsv

for nome in listacsv['Ticker']:
    empresas.append(nome)

print (empresas)

['COGN3', 'VALE3', 'ABEV3', 'BBAS3', 'RENT3', 'B3SA3', 'BBDC4', 'MGLU3', 'IFCM3', 'VAMO3', 'ITUB4', 'USIM5', 'ITSA4', 'MOVI3', 'TIMS3', 'PETR4', 'RADL3', 'PCAR3', 'VBBR3', 'AZUL4', 'LREN3', 'RAIZ4', 'CSAN3', 'MRVE3', 'CMIG4', 'SIMH3', 'WEGE3', 'NTCO3', 'ENEV3', 'BEEF3', 'CPLE6', 'CVCB3', 'PRIO3', 'HAPV3', 'RAIL3', 'BRAV3', 'POMO4', 'GGBR4', 'SUZB3', 'PETZ3', 'BBDC3', 'CSNA3', 'CPLE3', 'CBAV3', 'MOTV3', 'ASAI3', 'PETR3', 'VIVT3', 'MRFG3', 'EQTL3', 'BPAC11', 'LWSA3', 'CMIN3', 'IGTI11', 'IGTI11', 'UGPA3', 'ANIM3', 'QUAL3', 'SRNA3', 'GOAU4', 'VIVA3', 'RDOR3', 'ALOS3', 'KLBN11', 'BHIA3', 'BRKM5', 'BRAP4', 'MULT3', 'HBSA3', 'BRFS3', 'EMBR3', 'AZTE3', 'SANB11', 'CYRE3', 'LIGT3', 'PDGR3', 'ELET3', 'CXSE3', 'INTB3', 'JHSF3', 'RCSL4', 'CASH3', 'CSMG3', 'SMFT3', 'CEAB3', 'GGPS3', 'HYPE3', 'MILS3', 'AZZA3', 'AMER3', 'SAPR11', 'ECOR3', 'BBSE3', 'FLRY3', 'TOTS3', 'ONCO3', 'SLCE3', 'AURE3', 'SMTO3', 'KLBN4', 'DIRR3', 'NEOE3', 'GMAT3', 'TEND3', 'STBP3', 'PSSA3', 'SAPR4', 'SBSP3', 'CURY3', 'RECV3', 'RAPT4', 'DXCO3', 'CPFE3', 'ODPV3', 'EZTC3', 'HBOR3', 'ENGI11', 'YDUQ3', 'TTEN3', 'SEQL3', 'LJQQ3', 'SEER3', 'ENJU3', 'PLPL3', 'ALPA4', 'DASA3', 'MELK3', 'ELET6', 'SBFG3', 'TAEE11', 'MYPK3', 'EGIE3', 'MDNE3', 'GRND3', 'RANI3', 'ARML3', 'LAVV3', 'BMGB4', 'ABCB4', 'PGMN3', 'ISAE4', 'AZEV4', 'IRBR3', 'VVEO3', 'BRSR6', 'ALUP11', 'CAML3', 'GUAR3', 'MLAS3', 'SYNE3', 'VULC3', 'OIBR3', 'KEPL3', 'POSI3', 'BPAN4', 'MTRE3', 'JALL3', 'SHUL4', 'MDIA3', 'USIM3', 'AZEV3', 'TFCO4', 'ORVR3', 'FRAS3', 'ITUB3', 'PRNR3', 'JSLG3', 'AERI3', 'ZAMP3', 'TUPY3', 'FESA4', 'SOJA3', 'BMOB3', 'WIZC3', 'SAPR3', 'RCSL3', 'KLBN3', 'PORT3', 'EVEN3', 'GFSA3', 'CSED3', 'TASA4', 'VTRU3', 'VLID3', 'PNVL3', 'OPCT3', 'HBRE3', 'TRIS3', 'PTBL3', 'TGMA3', 'AMBP3', 'VITT3', 'LEVE3', 'UNIP6', 'FIQE3', 'AGRO3', 'BLAU3', 'LOGG3', 'AMAR3', 'ESPA3', 'PFRM3', 'BRBI11', 'AMOB3', 'BRST3', 'POMO3', 'PMAM3', 'PINE4', 'MEAL3', 'DEXP3', 'ROMI3', 'MATD3', 'TAEE4', 'DESK3', 'TECN3', 'CMIG3', 'SANB3', 'RNEW4', 'BIOM3', 'RNEW3', 'EUCA4', 'BRAP3', 'ALPK3', 'ITSA3', 'CAMB3', 'FHER3', 'OIBR4', 'LAND3', 'SANB4', 'DMVF3', 'LPSB3', 'IGTI3', 'IGTI3', 'TAEE3', 'ETER3', 'LUPA3', 'SHOW3', 'TCSA3', 'BRKM3', 'SCAR3', 'ALLD3', 'LVTC3', 'VIVR3', 'HAGA4', 'CSUD3', 'CEBR3', 'AZEV11', 'VSTE3', 'WEST3', 'PDTC3', 'EALT4', 'TASA3', 'AALR3', 'TRAD3', 'PTNT4', 'FICT3', 'GGBR3', 'BMEB4', 'AGXY3', 'WHRL4', 'DEXP4', 'GOAU3', 'UCAS3', 'INEP3', 'RSID3', 'MTSA4', 'WHRL3', 'RNEW11', 'CTSA4', 'AMAR11', 'NGRD3', 'DOTZ3', 'CGRA4', 'INEP4', 'CGRA3', 'REAG3', 'RAPT3', 'BAZA3', 'SNSY5', 'LOGN3', 'BIED3', 'CEBR6', 'CTSA3', 'CRPG5', 'ALUP3', 'BPAC5', 'BEES3', 'ENGI4', 'EQPA3', 'EMAE4', 'ALUP4', 'CEBR5', 'ALPA3', 'BEES4', 'UNIP3', 'ATED3', 'BOBR4', 'EPAR3', 'AVLL3', 'WLMM4', 'MNPR3', 'CLSC4', 'ENMT3', 'RPMG3', 'ENGI3', 'BRSR3', 'TPIS3', 'MAPT4', 'MGEL4', 'RSUL4', 'OFSA3', 'REDE3', 'NUTR3', 'CPLE5', 'COCE5', 'TELB4', 'BRKM6', 'BAUH4', 'BGIP4', 'GSHP3', 'RDNI3', 'ISAE3', 'MWET4', 'BSLI4', 'JFEN3', 'CBEE3', 'OSXB3', 'PINE3', 'CEDO3', 'BDLL4', 'NEXP3', 'HAGA3', 'PATI4', 'BPAC3', 'PLAS3', 'FRIO3', 'EUCA3', 'SNSY3', 'CRPG6', 'CEDO4', 'BALM4', 'HOOT4', 'PPLA11', 'CGAS5', 'CCTY3', 'CRPG3', 'EALT3', 'BRSR5', 'PINE11', 'IGTI4', 'IGTI4', 'PTNT3', 'BSLI3', 'HETA4', 'BMKS3', 'FIEI3', 'MNDL3', 'BALM3', 'MOAR3', 'AFLT3', 'EKTR4', 'DOHL4', 'GEPA4', 'BGIP3', 'TELB3', 'TKNO4', 'GEPA3', 'MRSA3B', 'USIM6', 'ESTR4', 'EQMA3B', 'CEEB3', 'CTKA4', 'PATI3', 'RPAD6', 'BNBR3', 'UNIP5', 'LUXM4', 'RPAD3', 'FESA3', 'CGAS3', 'CLSC3', 'MTSA3', 'AHEB5', 'NORD3', 'PSVM11', 'SOND6', 'EKTR3', 'DTCY3', 'AHEB3', 'JOPA3', 'BMEB3', 'MWET3', 'COCE3', 'BMIN4', 'ELET5', 'PEAB3', 'CEED3', 'RPAD5']

In [12]:
# Removendo códigos com final 11 

for nome in empresas:
    tam=len(nome)
    if tam>5:
        empresas.remove(nome)
empresas.sort()
qtd = len(empresas)
print(qtd,empresas)

380 ['AALR3', 'ABCB4', 'ABEV3', 'AERI3', 'AFLT3', 'AGRO3', 'AGXY3', 'AHEB3', 'AHEB5', 'ALLD3', 'ALOS3', 'ALPA3', 'ALPA4', 'ALPK3', 'ALUP3', 'ALUP4', 'AMAR3', 'AMBP3', 'AMER3', 'AMOB3', 'ANIM3', 'ARML3', 'ASAI3', 'ATED3', 'AURE3', 'AVLL3', 'AZEV3', 'AZEV4', 'AZTE3', 'AZUL4', 'AZZA3', 'B3SA3', 'BALM3', 'BALM4', 'BAUH4', 'BAZA3', 'BBAS3', 'BBDC3', 'BBDC4', 'BBSE3', 'BDLL4', 'BEEF3', 'BEES3', 'BEES4', 'BGIP3', 'BGIP4', 'BHIA3', 'BIED3', 'BIOM3', 'BLAU3', 'BMEB3', 'BMEB4', 'BMGB4', 'BMIN4', 'BMKS3', 'BMOB3', 'BNBR3', 'BOBR4', 'BPAC3', 'BPAC5', 'BPAN4', 'BRAP3', 'BRAP4', 'BRAV3', 'BRFS3', 'BRKM3', 'BRKM5', 'BRKM6', 'BRSR3', 'BRSR5', 'BRSR6', 'BRST3', 'BSLI3', 'BSLI4', 'CAMB3', 'CAML3', 'CASH3', 'CBAV3', 'CBEE3', 'CCTY3', 'CEAB3', 'CEBR3', 'CEBR5', 'CEBR6', 'CEDO3', 'CEDO4', 'CEEB3', 'CEED3', 'CGAS3', 'CGAS5', 'CGRA3', 'CGRA4', 'CLSC3', 'CLSC4', 'CMIG3', 'CMIG4', 'CMIN3', 'COCE3', 'COCE5', 'COGN3', 'CPFE3', 'CPLE3', 'CPLE5', 'CPLE6', 'CRPG3', 'CRPG5', 'CRPG6', 'CSAN3', 'CSED3', 'CSMG3', 'CSNA3', 'CSUD3', 'CTKA4', 'CTSA3', 'CTSA4', 'CURY3', 'CVCB3', 'CXSE3', 'CYRE3', 'DASA3', 'DESK3', 'DEXP3', 'DEXP4', 'DIRR3', 'DMVF3', 'DOHL4', 'DOTZ3', 'DTCY3', 'DXCO3', 'EALT3', 'EALT4', 'ECOR3', 'EGIE3', 'EKTR3', 'EKTR4', 'ELET3', 'ELET5', 'ELET6', 'EMAE4', 'EMBR3', 'ENEV3', 'ENGI3', 'ENGI4', 'ENJU3', 'ENMT3', 'EPAR3', 'EQPA3', 'EQTL3', 'ESPA3', 'ESTR4', 'ETER3', 'EUCA3', 'EUCA4', 'EVEN3', 'EZTC3', 'FESA3', 'FESA4', 'FHER3', 'FICT3', 'FIEI3', 'FIQE3', 'FLRY3', 'FRAS3', 'FRIO3', 'GEPA3', 'GEPA4', 'GFSA3', 'GGBR3', 'GGBR4', 'GGPS3', 'GMAT3', 'GOAU3', 'GOAU4', 'GRND3', 'GSHP3', 'GUAR3', 'HAGA3', 'HAGA4', 'HAPV3', 'HBOR3', 'HBRE3', 'HBSA3', 'HETA4', 'HOOT4', 'HYPE3', 'IFCM3', 'IGTI3', 'IGTI3', 'IGTI4', 'IGTI4', 'INEP3', 'INEP4', 'INTB3', 'IRBR3', 'ISAE3', 'ISAE4', 'ITSA3', 'ITSA4', 'ITUB3', 'ITUB4', 'JALL3', 'JFEN3', 'JHSF3', 'JOPA3', 'JSLG3', 'KEPL3', 'KLBN3', 'KLBN4', 'LAND3', 'LAVV3', 'LEVE3', 'LIGT3', 'LJQQ3', 'LOGG3', 'LOGN3', 'LPSB3', 'LREN3', 'LUPA3', 'LUXM4', 'LVTC3', 'LWSA3', 'MAPT4', 'MATD3', 'MDIA3', 'MDNE3', 'MEAL3', 'MELK3', 'MGEL4', 'MGLU3', 'MILS3', 'MLAS3', 'MNDL3', 'MNPR3', 'MOAR3', 'MOTV3', 'MOVI3', 'MRFG3', 'MRVE3', 'MTRE3', 'MTSA3', 'MTSA4', 'MULT3', 'MWET3', 'MWET4', 'MYPK3', 'NEOE3', 'NEXP3', 'NGRD3', 'NORD3', 'NTCO3', 'NUTR3', 'ODPV3', 'OFSA3', 'OIBR3', 'OIBR4', 'ONCO3', 'OPCT3', 'ORVR3', 'OSXB3', 'PATI3', 'PATI4', 'PCAR3', 'PDGR3', 'PDTC3', 'PEAB3', 'PETR3', 'PETR4', 'PETZ3', 'PFRM3', 'PGMN3', 'PINE3', 'PINE4', 'PLAS3', 'PLPL3', 'PMAM3', 'PNVL3', 'POMO3', 'POMO4', 'PORT3', 'POSI3', 'PRIO3', 'PRNR3', 'PSSA3', 'PTBL3', 'PTNT3', 'PTNT4', 'QUAL3', 'RADL3', 'RAIL3', 'RAIZ4', 'RANI3', 'RAPT3', 'RAPT4', 'RCSL3', 'RCSL4', 'RDNI3', 'RDOR3', 'REAG3', 'RECV3', 'REDE3', 'RENT3', 'RNEW3', 'RNEW4', 'ROMI3', 'RPAD3', 'RPAD5', 'RPAD6', 'RPMG3', 'RSID3', 'RSUL4', 'SANB3', 'SANB4', 'SAPR3', 'SAPR4', 'SBFG3', 'SBSP3', 'SCAR3', 'SEER3', 'SEQL3', 'SHOW3', 'SHUL4', 'SIMH3', 'SLCE3', 'SMFT3', 'SMTO3', 'SNSY3', 'SNSY5', 'SOJA3', 'SOND6', 'SRNA3', 'STBP3', 'SUZB3', 'SYNE3', 'TAEE3', 'TAEE4', 'TASA3', 'TASA4', 'TCSA3', 'TECN3', 'TELB3', 'TELB4', 'TEND3', 'TFCO4', 'TGMA3', 'TIMS3', 'TKNO4', 'TOTS3', 'TPIS3', 'TRAD3', 'TRIS3', 'TTEN3', 'TUPY3', 'UCAS3', 'UGPA3', 'UNIP3', 'UNIP5', 'UNIP6', 'USIM3', 'USIM5', 'USIM6', 'VALE3', 'VAMO3', 'VBBR3', 'VITT3', 'VIVA3', 'VIVR3', 'VIVT3', 'VLID3', 'VSTE3', 'VTRU3', 'VULC3', 'VVEO3', 'WEGE3', 'WEST3', 'WHRL3', 'WHRL4', 'WIZC3', 'WLMM4', 'YDUQ3', 'ZAMP3']

In [13]:
# Acrescentar ".SA" nos tickers das empresas - Padrão YFinance de busca

ticker = []
for empresa in empresas:
    empresa = f'{empresa}.SA'
    ticker.append(empresa)

print (ticker)

['AALR3.SA', 'ABCB4.SA', 'ABEV3.SA', 'AERI3.SA', 'AFLT3.SA', 'AGRO3.SA', 'AGXY3.SA', 'AHEB3.SA', 'AHEB5.SA', 'ALLD3.SA', 'ALOS3.SA', 'ALPA3.SA', 'ALPA4.SA', 'ALPK3.SA', 'ALUP3.SA', 'ALUP4.SA', 'AMAR3.SA', 'AMBP3.SA', 'AMER3.SA', 'AMOB3.SA', 'ANIM3.SA', 'ARML3.SA', 'ASAI3.SA', 'ATED3.SA', 'AURE3.SA', 'AVLL3.SA', 'AZEV3.SA', 'AZEV4.SA', 'AZTE3.SA', 'AZUL4.SA', 'AZZA3.SA', 'B3SA3.SA', 'BALM3.SA', 'BALM4.SA', 'BAUH4.SA', 'BAZA3.SA', 'BBAS3.SA', 'BBDC3.SA', 'BBDC4.SA', 'BBSE3.SA', 'BDLL4.SA', 'BEEF3.SA', 'BEES3.SA', 'BEES4.SA', 'BGIP3.SA', 'BGIP4.SA', 'BHIA3.SA', 'BIED3.SA', 'BIOM3.SA', 'BLAU3.SA', 'BMEB3.SA', 'BMEB4.SA', 'BMGB4.SA', 'BMIN4.SA', 'BMKS3.SA', 'BMOB3.SA', 'BNBR3.SA', 'BOBR4.SA', 'BPAC3.SA', 'BPAC5.SA', 'BPAN4.SA', 'BRAP3.SA', 'BRAP4.SA', 'BRAV3.SA', 'BRFS3.SA', 'BRKM3.SA', 'BRKM5.SA', 'BRKM6.SA', 'BRSR3.SA', 'BRSR5.SA', 'BRSR6.SA', 'BRST3.SA', 'BSLI3.SA', 'BSLI4.SA', 'CAMB3.SA', 'CAML3.SA', 'CASH3.SA', 'CBAV3.SA', 'CBEE3.SA', 'CCTY3.SA', 'CEAB3.SA', 'CEBR3.SA', 'CEBR5.SA', 'CEBR6.SA', 'CEDO3.SA', 'CEDO4.SA', 'CEEB3.SA', 'CEED3.SA', 'CGAS3.SA', 'CGAS5.SA', 'CGRA3.SA', 'CGRA4.SA', 'CLSC3.SA', 'CLSC4.SA', 'CMIG3.SA', 'CMIG4.SA', 'CMIN3.SA', 'COCE3.SA', 'COCE5.SA', 'COGN3.SA', 'CPFE3.SA', 'CPLE3.SA', 'CPLE5.SA', 'CPLE6.SA', 'CRPG3.SA', 'CRPG5.SA', 'CRPG6.SA', 'CSAN3.SA', 'CSED3.SA', 'CSMG3.SA', 'CSNA3.SA', 'CSUD3.SA', 'CTKA4.SA', 'CTSA3.SA', 'CTSA4.SA', 'CURY3.SA', 'CVCB3.SA', 'CXSE3.SA', 'CYRE3.SA', 'DASA3.SA', 'DESK3.SA', 'DEXP3.SA', 'DEXP4.SA', 'DIRR3.SA', 'DMVF3.SA', 'DOHL4.SA', 'DOTZ3.SA', 'DTCY3.SA', 'DXCO3.SA', 'EALT3.SA', 'EALT4.SA', 'ECOR3.SA', 'EGIE3.SA', 'EKTR3.SA', 'EKTR4.SA', 'ELET3.SA', 'ELET5.SA', 'ELET6.SA', 'EMAE4.SA', 'EMBR3.SA', 'ENEV3.SA', 'ENGI3.SA', 'ENGI4.SA', 'ENJU3.SA', 'ENMT3.SA', 'EPAR3.SA', 'EQPA3.SA', 'EQTL3.SA', 'ESPA3.SA', 'ESTR4.SA', 'ETER3.SA', 'EUCA3.SA', 'EUCA4.SA', 'EVEN3.SA', 'EZTC3.SA', 'FESA3.SA', 'FESA4.SA', 'FHER3.SA', 'FICT3.SA', 'FIEI3.SA', 'FIQE3.SA', 'FLRY3.SA', 'FRAS3.SA', 'FRIO3.SA', 'GEPA3.SA', 'GEPA4.SA', 'GFSA3.SA', 'GGBR3.SA', 'GGBR4.SA', 'GGPS3.SA', 'GMAT3.SA', 'GOAU3.SA', 'GOAU4.SA', 'GRND3.SA', 'GSHP3.SA', 'GUAR3.SA', 'HAGA3.SA', 'HAGA4.SA', 'HAPV3.SA', 'HBOR3.SA', 'HBRE3.SA', 'HBSA3.SA', 'HETA4.SA', 'HOOT4.SA', 'HYPE3.SA', 'IFCM3.SA', 'IGTI3.SA', 'IGTI3.SA', 'IGTI4.SA', 'IGTI4.SA', 'INEP3.SA', 'INEP4.SA', 'INTB3.SA', 'IRBR3.SA', 'ISAE3.SA', 'ISAE4.SA', 'ITSA3.SA', 'ITSA4.SA', 'ITUB3.SA', 'ITUB4.SA', 'JALL3.SA', 'JFEN3.SA', 'JHSF3.SA', 'JOPA3.SA', 'JSLG3.SA', 'KEPL3.SA', 'KLBN3.SA', 'KLBN4.SA', 'LAND3.SA', 'LAVV3.SA', 'LEVE3.SA', 'LIGT3.SA', 'LJQQ3.SA', 'LOGG3.SA', 'LOGN3.SA', 'LPSB3.SA', 'LREN3.SA', 'LUPA3.SA', 'LUXM4.SA', 'LVTC3.SA', 'LWSA3.SA', 'MAPT4.SA', 'MATD3.SA', 'MDIA3.SA', 'MDNE3.SA', 'MEAL3.SA', 'MELK3.SA', 'MGEL4.SA', 'MGLU3.SA', 'MILS3.SA', 'MLAS3.SA', 'MNDL3.SA', 'MNPR3.SA', 'MOAR3.SA', 'MOTV3.SA', 'MOVI3.SA', 'MRFG3.SA', 'MRVE3.SA', 'MTRE3.SA', 'MTSA3.SA', 'MTSA4.SA', 'MULT3.SA', 'MWET3.SA', 'MWET4.SA', 'MYPK3.SA', 'NEOE3.SA', 'NEXP3.SA', 'NGRD3.SA', 'NORD3.SA', 'NTCO3.SA', 'NUTR3.SA', 'ODPV3.SA', 'OFSA3.SA', 'OIBR3.SA', 'OIBR4.SA', 'ONCO3.SA', 'OPCT3.SA', 'ORVR3.SA', 'OSXB3.SA', 'PATI3.SA', 'PATI4.SA', 'PCAR3.SA', 'PDGR3.SA', 'PDTC3.SA', 'PEAB3.SA', 'PETR3.SA', 'PETR4.SA', 'PETZ3.SA', 'PFRM3.SA', 'PGMN3.SA', 'PINE3.SA', 'PINE4.SA', 'PLAS3.SA', 'PLPL3.SA', 'PMAM3.SA', 'PNVL3.SA', 'POMO3.SA', 'POMO4.SA', 'PORT3.SA', 'POSI3.SA', 'PRIO3.SA', 'PRNR3.SA', 'PSSA3.SA', 'PTBL3.SA', 'PTNT3.SA', 'PTNT4.SA', 'QUAL3.SA', 'RADL3.SA', 'RAIL3.SA', 'RAIZ4.SA', 'RANI3.SA', 'RAPT3.SA', 'RAPT4.SA', 'RCSL3.SA', 'RCSL4.SA', 'RDNI3.SA', 'RDOR3.SA', 'REAG3.SA', 'RECV3.SA', 'REDE3.SA', 'RENT3.SA', 'RNEW3.SA', 'RNEW4.SA', 'ROMI3.SA', 'RPAD3.SA', 'RPAD5.SA', 'RPAD6.SA', 'RPMG3.SA', 'RSID3.SA', 'RSUL4.SA', 'SANB3.SA', 'SANB4.SA', 'SAPR3.SA', 'SAPR4.SA', 'SBFG3.SA', 'SBSP3.SA', 'SCAR3.SA', 'SEER3.SA', 'SEQL3.SA', 'SHOW3.SA', 'SHUL4.SA', 'SIMH3.SA', 'SLCE3.SA', 'SMFT3.SA', 'SMTO3.SA', 'SNSY3.SA', 'SNSY5.SA', 'SOJA3.SA', 'SOND6.SA', 'SRNA3.SA', 'STBP3.SA', 'SUZB3.SA', 'SYNE3.SA', 'TAEE3.SA', 'TAEE4.SA', 'TASA3.SA', 'TASA4.SA', 'TCSA3.SA', 'TECN3.SA', 'TELB3.SA', 'TELB4.SA', 'TEND3.SA', 'TFCO4.SA', 'TGMA3.SA', 'TIMS3.SA', 'TKNO4.SA', 'TOTS3.SA', 'TPIS3.SA', 'TRAD3.SA', 'TRIS3.SA', 'TTEN3.SA', 'TUPY3.SA', 'UCAS3.SA', 'UGPA3.SA', 'UNIP3.SA', 'UNIP5.SA', 'UNIP6.SA', 'USIM3.SA', 'USIM5.SA', 'USIM6.SA', 'VALE3.SA', 'VAMO3.SA', 'VBBR3.SA', 'VITT3.SA', 'VIVA3.SA', 'VIVR3.SA', 'VIVT3.SA', 'VLID3.SA', 'VSTE3.SA', 'VTRU3.SA', 'VULC3.SA', 'VVEO3.SA', 'WEGE3.SA', 'WEST3.SA', 'WHRL3.SA', 'WHRL4.SA', 'WIZC3.SA', 'WLMM4.SA', 'YDUQ3.SA', 'ZAMP3.SA']

# Pegar cotação histórica (Apenas o preço de fechamento "Close")

In [46]:

inicio = "2010-01-02"
fim = "2024-07-01"

cotacao_df=yf.download(tickers=ticker, start=inicio, end=fim)["Close"]
    

display(cotacao_df)

C:\Users\tiakk\AppData\Local\Temp\ipykernel_14468\4135123447.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  cotacao_df=yf.download(tickers=ticker, start=inicio, end=fim)["Close"]
[*********************100%***********************]  378 of 378 completed

10 Failed downloads:
['MOTV3.SA', 'BSLI4.SA', 'AMOB3.SA', 'ATED3.SA', 'BIED3.SA', 'BRST3.SA', 'AZTE3.SA', 'CCTY3.SA']: YFPricesMissingError('possibly delisted; no price data found  (1d 2010-01-02 -> 2024-07-01) (Yahoo error = "Data doesn\'t exist for startDate = 1262397600, endDate = 1719802800")')
['LEVE3.SA']: Timeout('Failed to perform, curl: (28) Operation timed out after 10010 milliseconds with 0 bytes received. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
['UNIP5.SA']: Timeout('Failed to perform, curl: (28) Connection timed out after 10009 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')

Ticker,AALR3.SA,ABCB4.SA,ABEV3.SA,AERI3.SA,AFLT3.SA,AGRO3.SA,AGXY3.SA,AHEB3.SA,AHEB5.SA,ALLD3.SA,...,VULC3.SA,VVEO3.SA,WEGE3.SA,WEST3.SA,WHRL3.SA,WHRL4.SA,WIZC3.SA,WLMM4.SA,YDUQ3.SA,ZAMP3.SA
Date,,,,,,,,,,,,,,,,,,,,,
2010-01-04,NaN,3.626091,3.584094,NaN,6.608785,4.894166,NaN,22.192442,9.843130,NaN,...,17.140347,NaN,2.003208,NaN,1.002833,1.123209,NaN,4.919768,5.319603,NaN
2010-01-05,NaN,3.722983,3.605177,NaN,6.608785,4.894166,NaN,22.192442,9.843130,NaN,...,17.346027,NaN,1.998835,NaN,1.002833,1.113637,NaN,4.919768,5.383323,NaN
2010-01-06,NaN,3.784641,3.641955,NaN,6.608785,4.894166,NaN,22.192442,9.843130,NaN,...,17.140347,NaN,2.009763,NaN,1.002833,1.097682,NaN,5.106594,5.471215,NaN
2010-01-07,NaN,3.728856,3.659056,NaN,6.608785,5.033314,NaN,22.192442,9.843130,NaN,...,17.620277,NaN,2.043643,NaN,1.002833,1.094491,NaN,5.125278,5.383323,NaN
2010-01-08,NaN,3.699494,3.652028,NaN,6.608785,5.033314,NaN,22.192442,9.843130,NaN,...,17.620277,NaN,2.117957,NaN,1.002833,1.100873,NaN,5.293422,5.383323,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-06-24,10.10,19.019600,11.114491,5.59,7.256919,24.165785,13.499999,27.500000,19.200001,7.45,...,13.550424,2.07,40.134159,9.0,3.913821,3.887461,5.589578,29.649946,10.675753,3.82
2024-06-25,10.06,19.591421,11.173403,5.16,7.256919,24.240776,15.899999,27.500000,19.200001,7.35,...,13.458744,2.11,40.821560,8.9,3.896389,3.852751,5.503290,29.126711,10.368261,3.62
2024-06-26,10.41,19.169153,11.242131,5.09,7.007795,24.118916,14.999999,27.500000,19.200001,7.43,...,13.385400,2.12,41.194717,8.6,3.861521,3.835397,5.464939,29.834049,10.233732,3.57
2024-06-27,10.48,19.600216,11.251950,5.26,7.066932,24.137663,15.449999,27.500000,19.200001,7.35,...,13.669609,2.32,40.949219,8.7,3.852805,3.844074,5.608753,30.037527,10.608489,3.78
2024-06-28,10.39,19.477057,11.202857,5.10,7.086645,24.034550,15.749999,31.000000,19.200001,7.45,...,13.559592,2.24,41.430393,8.7,3.861521,3.948202,5.474527,30.425110,10.003114,3.74

In [47]:
cotacao_df.to_excel('cotacoes.xlsx')

In [63]:
# Remover ".SA" dos nomes das empresas nas colunas da tabela
df = pd.read_excel("cotacoes.xlsx")

cotacoes_df = df
#display(cotacoes_df)
for empresa in cotacoes_df.columns:
    if empresa == "Date":
        pass
    
    else:
    
        novonome = empresa[-8:-3]

        #print(novonome)
        cotacoes_df.rename(columns={f'{empresa}': f'{novonome}'}, inplace=True)

cotacoes_df = cotacoes_df.set_index('Date') 

display(cotacoes_df)

,AALR3,ABCB4,ABEV3,AERI3,AESB3,AFLT3,AGRO3,AGXY3,AHEB3,ALLD3,...,VSTE3,VULC3,VVEO3,WEGE3,WEST3,WHRL4,WIZC3,WLMM4,YDUQ3,ZAMP3
Date,,,,,,,,,,,,,,,,,,,,,
2010-01-04,NaN,3.626092,3.386008,NaN,NaN,6.859030,4.894166,NaN,22.192442,NaN,...,120.015137,17.140339,NaN,2.003207,NaN,1.004303,NaN,4.982957,5.535982,NaN
2010-01-05,NaN,3.722983,3.405926,NaN,NaN,6.859030,4.894166,NaN,22.192442,NaN,...,117.826347,17.346025,NaN,1.998836,NaN,0.995743,NaN,4.982957,5.602295,NaN
2010-01-06,NaN,3.784642,3.440670,NaN,NaN,6.859030,4.894166,NaN,22.192442,NaN,...,117.096779,17.140339,NaN,2.009764,NaN,0.981478,NaN,5.172183,5.693761,NaN
2010-01-07,NaN,3.728855,3.456827,NaN,NaN,6.859030,5.033314,NaN,22.192442,NaN,...,116.732040,17.620274,NaN,2.043643,NaN,0.978625,NaN,5.191106,5.602295,NaN
2010-01-08,NaN,3.699495,3.450187,NaN,NaN,6.859030,5.033314,NaN,22.192442,NaN,...,116.549606,17.620274,NaN,2.117956,NaN,0.984331,NaN,5.361410,5.602295,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-06-24,10.10,19.019602,10.533895,5.59,NaN,7.256919,24.165785,13.499999,27.500000,6.361814,...,17.086391,13.550424,2.07,40.134163,9.0,3.887461,5.589578,29.649946,11.110000,3.82
2024-06-25,10.06,19.591419,10.589728,5.16,NaN,7.256919,24.240776,15.899999,27.500000,6.276421,...,17.196369,13.458743,2.11,40.821556,8.9,3.852751,5.503290,29.126713,10.790000,3.62
2024-06-26,10.41,19.169155,10.654867,5.09,NaN,7.007795,24.118916,14.999999,27.500000,6.344735,...,17.086391,13.385399,2.12,41.194721,8.6,3.835397,5.464939,29.834047,10.650000,3.57
2024-06-27,10.48,19.600218,10.664172,5.26,NaN,7.066933,24.137663,15.449999,27.500000,6.276421,...,17.096390,13.669609,2.32,40.949219,8.7,3.844074,5.608753,30.037527,11.040000,3.78
2024-06-28,10.39,19.477055,10.617644,5.10,NaN,7.086645,24.034550,15.749999,31.000000,6.361814,...,17.096390,13.559592,2.24,41.430393,8.7,3.948202,5.474527,30.425108,10.410000,3.74

In [64]:
# Separar as cotações em tabelas de cada empresa 

for empresa in cotacoes_df:
    if empresa == 'Date':
        pass
    else:
        tabela = cotacoes_df[empresa]
       
        cotacao = tabela.to_excel(f'./cotacoes/{empresa}.xlsx')

In [65]:
# Criando coluna "Empresa" para facilitar concatenamento futurono projeto

lista_tab = os.listdir("./cotacoes")


lista_tab

for empresa in lista_tab:
    
    if empresa == '.ipynb_checkpoints':
        pass
    else:
    
        df = pd.read_excel(f'./cotacoes/{empresa}')
        nm = f'{empresa}'[-10:-5]
     
        df.rename(columns = {nm :'Close'}, inplace=True)
        df.loc[:, 'Empresa'] = (f'{nm}')
        #df = df.drop("Unnamed: 0", axis=1)
        df = df.set_index('Date')
        
        tabela = df
       
        cotacao = tabela.to_excel(f'./cotacoes/{nm}.xlsx')
        display(df)

            Close Empresa
Date
2010-01-04    NaN   AALR3
2010-01-05    NaN   AALR3
2010-01-06    NaN   AALR3
2010-01-07    NaN   AALR3
2010-01-08    NaN   AALR3
...           ...     ...
2024-06-24  10.10   AALR3
2024-06-25  10.06   AALR3
2024-06-26  10.41   AALR3
2024-06-27  10.48   AALR3
2024-06-28  10.39   AALR3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   3.626092   ABCB4
2010-01-05   3.722983   ABCB4
2010-01-06   3.784642   ABCB4
2010-01-07   3.728855   ABCB4
2010-01-08   3.699495   ABCB4
...               ...     ...
2024-06-24  19.019602   ABCB4
2024-06-25  19.591419   ABCB4
2024-06-26  19.169155   ABCB4
2024-06-27  19.600218   ABCB4
2024-06-28  19.477055   ABCB4

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   3.386008   ABEV3
2010-01-05   3.405926   ABEV3
2010-01-06   3.440670   ABEV3
2010-01-07   3.456827   ABEV3
2010-01-08   3.450187   ABEV3
...               ...     ...
2024-06-24  10.533895   ABEV3
2024-06-25  10.589728   ABEV3
2024-06-26  10.654867   ABEV3
2024-06-27  10.664172   ABEV3
2024-06-28  10.617644   ABEV3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   AERI3
2010-01-05    NaN   AERI3
2010-01-06    NaN   AERI3
2010-01-07    NaN   AERI3
2010-01-08    NaN   AERI3
...           ...     ...
2024-06-24   5.59   AERI3
2024-06-25   5.16   AERI3
2024-06-26   5.09   AERI3
2024-06-27   5.26   AERI3
2024-06-28   5.10   AERI3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   AESB3
2010-01-05    NaN   AESB3
2010-01-06    NaN   AESB3
2010-01-07    NaN   AESB3
2010-01-08    NaN   AESB3
...           ...     ...
2024-06-24    NaN   AESB3
2024-06-25    NaN   AESB3
2024-06-26    NaN   AESB3
2024-06-27    NaN   AESB3
2024-06-28    NaN   AESB3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  6.859030   AFLT3
2010-01-05  6.859030   AFLT3
2010-01-06  6.859030   AFLT3
2010-01-07  6.859030   AFLT3
2010-01-08  6.859030   AFLT3
...              ...     ...
2024-06-24  7.256919   AFLT3
2024-06-25  7.256919   AFLT3
2024-06-26  7.007795   AFLT3
2024-06-27  7.066933   AFLT3
2024-06-28  7.086645   AFLT3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   4.894166   AGRO3
2010-01-05   4.894166   AGRO3
2010-01-06   4.894166   AGRO3
2010-01-07   5.033314   AGRO3
2010-01-08   5.033314   AGRO3
...               ...     ...
2024-06-24  24.165785   AGRO3
2024-06-25  24.240776   AGRO3
2024-06-26  24.118916   AGRO3
2024-06-27  24.137663   AGRO3
2024-06-28  24.034550   AGRO3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04        NaN   AGXY3
2010-01-05        NaN   AGXY3
2010-01-06        NaN   AGXY3
2010-01-07        NaN   AGXY3
2010-01-08        NaN   AGXY3
...               ...     ...
2024-06-24  13.499999   AGXY3
2024-06-25  15.899999   AGXY3
2024-06-26  14.999999   AGXY3
2024-06-27  15.449999   AGXY3
2024-06-28  15.749999   AGXY3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  22.192442   AHEB3
2010-01-05  22.192442   AHEB3
2010-01-06  22.192442   AHEB3
2010-01-07  22.192442   AHEB3
2010-01-08  22.192442   AHEB3
...               ...     ...
2024-06-24  27.500000   AHEB3
2024-06-25  27.500000   AHEB3
2024-06-26  27.500000   AHEB3
2024-06-27  27.500000   AHEB3
2024-06-28  31.000000   AHEB3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04       NaN   ALLD3
2010-01-05       NaN   ALLD3
2010-01-06       NaN   ALLD3
2010-01-07       NaN   ALLD3
2010-01-08       NaN   ALLD3
...              ...     ...
2024-06-24  6.361814   ALLD3
2024-06-25  6.276421   ALLD3
2024-06-26  6.344735   ALLD3
2024-06-27  6.276421   ALLD3
2024-06-28  6.361814   ALLD3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04        NaN   ALOS3
2010-01-05        NaN   ALOS3
2010-01-06        NaN   ALOS3
2010-01-07        NaN   ALOS3
2010-01-08        NaN   ALOS3
...               ...     ...
2024-06-24  20.606226   ALOS3
2024-06-25  20.586878   ALOS3
2024-06-26  20.315996   ALOS3
2024-06-27  20.548183   ALOS3
2024-06-28  20.432091   ALOS3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  2.508362   ALPA4
2010-01-05  2.517086   ALPA4
2010-01-06  2.510543   ALPA4
2010-01-07  2.536717   ALPA4
2010-01-08  2.562890   ALPA4
...              ...     ...
2024-06-24  9.190000   ALPA4
2024-06-25  9.300000   ALPA4
2024-06-26  9.350000   ALPA4
2024-06-27  9.460000   ALPA4
2024-06-28  9.120000   ALPA4

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   ALPK3
2010-01-05    NaN   ALPK3
2010-01-06    NaN   ALPK3
2010-01-07    NaN   ALPK3
2010-01-08    NaN   ALPK3
...           ...     ...
2024-06-24   3.19   ALPK3
2024-06-25   3.30   ALPK3
2024-06-26   3.17   ALPK3
2024-06-27   3.28   ALPK3
2024-06-28   3.36   ALPK3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04       NaN   ALUP4
2010-01-05       NaN   ALUP4
2010-01-06       NaN   ALUP4
2010-01-07       NaN   ALUP4
2010-01-08       NaN   ALUP4
...              ...     ...
2024-06-24  9.638466   ALUP4
2024-06-25  9.543786   ALUP4
2024-06-26  9.477510   ALUP4
2024-06-27  9.449105   ALUP4
2024-06-28  9.430170   ALUP4

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  44.321712   AMAR3
2010-01-05  46.048534   AMAR3
2010-01-06  46.010155   AMAR3
2010-01-07  47.122993   AMAR3
2010-01-08  49.425423   AMAR3
...               ...     ...
2024-06-24   1.430000   AMAR3
2024-06-25   1.440000   AMAR3
2024-06-26   1.350000   AMAR3
2024-06-27   1.380000   AMAR3
2024-06-28   1.380000   AMAR3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   AMBP3
2010-01-05    NaN   AMBP3
2010-01-06    NaN   AMBP3
2010-01-07    NaN   AMBP3
2010-01-08    NaN   AMBP3
...           ...     ...
2024-06-24  10.18   AMBP3
2024-06-25  10.55   AMBP3
2024-06-26  11.20   AMBP3
2024-06-27  12.52   AMBP3
2024-06-28  12.90   AMBP3

[3597 rows x 2 columns]

                  Close Empresa
Date
2010-01-04  3970.352295   AMER3
2010-01-05  3875.596680   AMER3
2010-01-06  3918.279541   AMER3
2010-01-07  3962.669189   AMER3
2010-01-08  3867.913574   AMER3
...                 ...     ...
2024-06-24    41.000000   AMER3
2024-06-25    41.000000   AMER3
2024-06-26    40.000000   AMER3
2024-06-27    40.000000   AMER3
2024-06-28    39.000000   AMER3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04       NaN   ANIM3
2010-01-05       NaN   ANIM3
2010-01-06       NaN   ANIM3
2010-01-07       NaN   ANIM3
2010-01-08       NaN   ANIM3
...              ...     ...
2024-06-24  2.744748   ANIM3
2024-06-25  2.718855   ANIM3
2024-06-26  2.675698   ANIM3
2024-06-27  2.856955   ANIM3
2024-06-28  2.718855   ANIM3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   APER3
2010-01-05    NaN   APER3
2010-01-06    NaN   APER3
2010-01-07    NaN   APER3
2010-01-08    NaN   APER3
...           ...     ...
2024-06-24    NaN   APER3
2024-06-25    NaN   APER3
2024-06-26    NaN   APER3
2024-06-27    NaN   APER3
2024-06-28    NaN   APER3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04       NaN   ARML3
2010-01-05       NaN   ARML3
2010-01-06       NaN   ARML3
2010-01-07       NaN   ARML3
2010-01-08       NaN   ARML3
...              ...     ...
2024-06-24  9.553666   ARML3
2024-06-25  9.592034   ARML3
2024-06-26  9.390601   ARML3
2024-06-27  9.793467   ARML3
2024-06-28  9.457745   ARML3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   ARZZ3
2010-01-05    NaN   ARZZ3
2010-01-06    NaN   ARZZ3
2010-01-07    NaN   ARZZ3
2010-01-08    NaN   ARZZ3
...           ...     ...
2024-06-24    NaN   ARZZ3
2024-06-25    NaN   ARZZ3
2024-06-26    NaN   ARZZ3
2024-06-27    NaN   ARZZ3
2024-06-28    NaN   ARZZ3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04        NaN   ASAI3
2010-01-05        NaN   ASAI3
2010-01-06        NaN   ASAI3
2010-01-07        NaN   ASAI3
2010-01-08        NaN   ASAI3
...               ...     ...
2024-06-24  10.889648   ASAI3
2024-06-25  10.712582   ASAI3
2024-06-26  10.506002   ASAI3
2024-06-27  10.653559   ASAI3
2024-06-28  10.171542   ASAI3

[3597 rows x 2 columns]

                  Close Empresa
Date
2010-01-04  9677.533203   ATMP3
2010-01-05  9724.352539   ATMP3
2010-01-06  9769.372070   ATMP3
2010-01-07  9697.340820   ATMP3
2010-01-08  9796.384766   ATMP3
...                 ...     ...
2024-06-24     2.260000   ATMP3
2024-06-25     2.140000   ATMP3
2024-06-26     2.110000   ATMP3
2024-06-27     2.040000   ATMP3
2024-06-28     1.910000   ATMP3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   ATOM3
2010-01-05    NaN   ATOM3
2010-01-06    NaN   ATOM3
2010-01-07    NaN   ATOM3
2010-01-08    NaN   ATOM3
...           ...     ...
2024-06-24    NaN   ATOM3
2024-06-25    NaN   ATOM3
2024-06-26    NaN   ATOM3
2024-06-27    NaN   ATOM3
2024-06-28    NaN   ATOM3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04        NaN   AURE3
2010-01-05        NaN   AURE3
2010-01-06        NaN   AURE3
2010-01-07        NaN   AURE3
2010-01-08        NaN   AURE3
...               ...     ...
2024-06-24  12.257974   AURE3
2024-06-25  12.178505   AURE3
2024-06-26  12.158638   AURE3
2024-06-27  12.188439   AURE3
2024-06-28  12.257974   AURE3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   AVLL3
2010-01-05    NaN   AVLL3
2010-01-06    NaN   AVLL3
2010-01-07    NaN   AVLL3
2010-01-08    NaN   AVLL3
...           ...     ...
2024-06-24   3.45   AVLL3
2024-06-25   3.30   AVLL3
2024-06-26   3.34   AVLL3
2024-06-27   3.40   AVLL3
2024-06-28   3.35   AVLL3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  1.272496   AZEV4
2010-01-05  1.272496   AZEV4
2010-01-06  1.272496   AZEV4
2010-01-07  1.272496   AZEV4
2010-01-08  1.272496   AZEV4
...              ...     ...
2024-06-24  1.580000   AZEV4
2024-06-25  1.690000   AZEV4
2024-06-26  1.470000   AZEV4
2024-06-27  1.530000   AZEV4
2024-06-28  1.500000   AZEV4

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   AZUL4
2010-01-05    NaN   AZUL4
2010-01-06    NaN   AZUL4
2010-01-07    NaN   AZUL4
2010-01-08    NaN   AZUL4
...           ...     ...
2024-06-24   7.95   AZUL4
2024-06-25   7.74   AZUL4
2024-06-26   7.31   AZUL4
2024-06-27   7.81   AZUL4
2024-06-28   7.34   AZUL4

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   7.665872   B3SA3
2010-01-05   7.695467   B3SA3
2010-01-06   7.985526   B3SA3
2010-01-07   8.174954   B3SA3
2010-01-08   7.985526   B3SA3
...               ...     ...
2024-06-24  10.247573   B3SA3
2024-06-25  10.062316   B3SA3
2024-06-26   9.964815   B3SA3
2024-06-27  10.140320   B3SA3
2024-06-28   9.984315   B3SA3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   BAHI3
2010-01-05    NaN   BAHI3
2010-01-06    NaN   BAHI3
2010-01-07    NaN   BAHI3
2010-01-08    NaN   BAHI3
...           ...     ...
2024-06-24    NaN   BAHI3
2024-06-25    NaN   BAHI3
2024-06-26    NaN   BAHI3
2024-06-27    NaN   BAHI3
2024-06-28    NaN   BAHI3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  1.827439   BALM3
2010-01-05  2.313783   BALM3
2010-01-06  2.336884   BALM3
2010-01-07  2.336884   BALM3
2010-01-08  2.431722   BALM3
...              ...     ...
2024-06-24  9.353484   BALM3
2024-06-25  9.353484   BALM3
2024-06-26  9.353484   BALM3
2024-06-27  9.353484   BALM3
2024-06-28  9.353484   BALM3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   3.315637   BAUH4
2010-01-05   3.315637   BAUH4
2010-01-06   3.315637   BAUH4
2010-01-07   3.315637   BAUH4
2010-01-08   3.315637   BAUH4
...               ...     ...
2024-06-24  77.262024   BAUH4
2024-06-25  77.262024   BAUH4
2024-06-26  77.262024   BAUH4
2024-06-27  78.738556   BAUH4
2024-06-28  78.728722   BAUH4

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  19.979509   BAZA3
2010-01-05  20.584949   BAZA3
2010-01-06  19.676788   BAZA3
2010-01-07  19.979509   BAZA3
2010-01-08  23.914865   BAZA3
...               ...     ...
2024-06-24  79.099228   BAZA3
2024-06-25  79.099228   BAZA3
2024-06-26  80.380936   BAZA3
2024-06-27  82.047142   BAZA3
2024-06-28  81.479530   BAZA3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   5.932722   BBAS3
2010-01-05   5.873199   BBAS3
2010-01-06   5.881134   BBAS3
2010-01-07   5.883120   BBAS3
2010-01-08   5.916850   BBAS3
...               ...     ...
2024-06-24  25.431833   BBAS3
2024-06-25  25.507717   BBAS3
2024-06-26  25.336971   BBAS3
2024-06-27  25.327488   BBAS3
2024-06-28  25.336971   BBAS3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   6.931419   BBDC4
2010-01-05   6.897309   BBDC4
2010-01-06   6.842130   BBDC4
2010-01-07   6.823737   BBDC4
2010-01-08   6.816381   BBDC4
...               ...     ...
2024-06-24  11.325416   BBDC4
2024-06-25  11.234375   BBDC4
2024-06-26  11.261688   BBDC4
2024-06-27  11.307206   BBDC4
2024-06-28  11.270792   BBDC4

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04        NaN   BBSE3
2010-01-05        NaN   BBSE3
2010-01-06        NaN   BBSE3
2010-01-07        NaN   BBSE3
2010-01-08        NaN   BBSE3
...               ...     ...
2024-06-24  32.375610   BBSE3
2024-06-25  32.183071   BBSE3
2024-06-26  31.720974   BBSE3
2024-06-27  31.557312   BBSE3
2024-06-28  31.701719   BBSE3

[3597 rows x 2 columns]

                 Close Empresa
Date
2010-01-04  149.740173   BDLL3
2010-01-05  149.740173   BDLL3
2010-01-06  149.740173   BDLL3
2010-01-07  149.740173   BDLL3
2010-01-08  149.740173   BDLL3
...                ...     ...
2024-06-24   13.010000   BDLL3
2024-06-25   13.010000   BDLL3
2024-06-26   13.010000   BDLL3
2024-06-27   13.010000   BDLL3
2024-06-28   13.010000   BDLL3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  5.051656   BEEF3
2010-01-05  5.251291   BEEF3
2010-01-06  5.511687   BEEF3
2010-01-07  5.633204   BEEF3
2010-01-08  5.989076   BEEF3
...              ...     ...
2024-06-24  6.430000   BEEF3
2024-06-25  6.410000   BEEF3
2024-06-26  6.360000   BEEF3
2024-06-27  6.720000   BEEF3
2024-06-28  6.680000   BEEF3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  1.489538   BEES3
2010-01-05  1.483052   BEES3
2010-01-06  1.485214   BEES3
2010-01-07  1.470080   BEES3
2010-01-08  1.558718   BEES3
...              ...     ...
2024-06-24  8.194332   BEES3
2024-06-25  8.185031   BEES3
2024-06-26  8.371054   BEES3
2024-06-27  8.426861   BEES3
2024-06-28  8.428919   BEES3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   7.774031   BGIP3
2010-01-05   7.602182   BGIP3
2010-01-06   8.432777   BGIP3
2010-01-07   8.432777   BGIP3
2010-01-08   8.432777   BGIP3
...               ...     ...
2024-06-24  22.642344   BGIP3
2024-06-25  23.005888   BGIP3
2024-06-26  22.372015   BGIP3
2024-06-27  23.183002   BGIP3
2024-06-28  23.183002   BGIP3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  79.483742   BHIA3
2010-01-05  77.490265   BHIA3
2010-01-06  76.723534   BHIA3
2010-01-07  76.928001   BHIA3
2010-01-08  76.876884   BHIA3
...               ...     ...
2024-06-24   5.850000   BHIA3
2024-06-25   5.770000   BHIA3
2024-06-26   5.490000   BHIA3
2024-06-27   5.480000   BHIA3
2024-06-28   5.450000   BHIA3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   2.880251   BIOM3
2010-01-05   2.880251   BIOM3
2010-01-06   2.880251   BIOM3
2010-01-07   2.880251   BIOM3
2010-01-08   2.880251   BIOM3
...               ...     ...
2024-06-24  13.990000   BIOM3
2024-06-25  14.000000   BIOM3
2024-06-26  14.900000   BIOM3
2024-06-27  16.000000   BIOM3
2024-06-28  14.870000   BIOM3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04        NaN   BLAU3
2010-01-05        NaN   BLAU3
2010-01-06        NaN   BLAU3
2010-01-07        NaN   BLAU3
2010-01-08        NaN   BLAU3
...               ...     ...
2024-06-24   9.615763   BLAU3
2024-06-25   9.508050   BLAU3
2024-06-26   9.508050   BLAU3
2024-06-27  10.591771   BLAU3
2024-06-28  10.422859   BLAU3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   1.356790   BMEB4
2010-01-05   1.356790   BMEB4
2010-01-06   1.356790   BMEB4
2010-01-07   1.356790   BMEB4
2010-01-08   1.356790   BMEB4
...               ...     ...
2024-06-24  25.671082   BMEB4
2024-06-25  24.852993   BMEB4
2024-06-26  25.200914   BMEB4
2024-06-27  26.094231   BMEB4
2024-06-28  26.000196   BMEB4

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04       NaN   BMGB4
2010-01-05       NaN   BMGB4
2010-01-06       NaN   BMGB4
2010-01-07       NaN   BMGB4
2010-01-08       NaN   BMGB4
...              ...     ...
2024-06-24  2.918659   BMGB4
2024-06-25  2.973044   BMGB4
2024-06-26  2.900531   BMGB4
2024-06-27  2.918659   BMGB4
2024-06-28  3.109006   BMGB4

[3597 rows x 2 columns]

                 Close Empresa
Date
2010-01-04   96.187553   BMIN3
2010-01-05   96.187553   BMIN3
2010-01-06   96.187553   BMIN3
2010-01-07   96.187553   BMIN3
2010-01-08  109.331184   BMIN3
...                ...     ...
2024-06-24   20.010000   BMIN3
2024-06-25   20.000000   BMIN3
2024-06-26   20.000000   BMIN3
2024-06-27   20.000000   BMIN3
2024-06-28   20.000000   BMIN3

[3597 rows x 2 columns]

                 Close Empresa
Date
2010-01-04  129.974014   BMKS3
2010-01-05  129.974014   BMKS3
2010-01-06  129.974014   BMKS3
2010-01-07  129.974014   BMKS3
2010-01-08  129.974014   BMKS3
...                ...     ...
2024-06-24  319.300537   BMKS3
2024-06-25  319.300537   BMKS3
2024-06-26  294.474213   BMKS3
2024-06-27  308.083588   BMKS3
2024-06-28  312.859314   BMKS3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04        NaN   BMOB3
2010-01-05        NaN   BMOB3
2010-01-06        NaN   BMOB3
2010-01-07        NaN   BMOB3
2010-01-08        NaN   BMOB3
...               ...     ...
2024-06-24  12.404572   BMOB3
2024-06-25  12.771842   BMOB3
2024-06-26  12.588206   BMOB3
2024-06-27  12.670843   BMOB3
2024-06-28  12.487207   BMOB3

[3597 rows x 2 columns]

                 Close Empresa
Date
2010-01-04   15.990989   BNBR3
2010-01-05   15.990989   BNBR3
2010-01-06   15.990989   BNBR3
2010-01-07   15.990989   BNBR3
2010-01-08   15.990989   BNBR3
...                ...     ...
2024-06-24  109.400917   BNBR3
2024-06-25  109.400917   BNBR3
2024-06-26  109.400917   BNBR3
2024-06-27  109.400917   BNBR3
2024-06-28  109.400917   BNBR3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04   5.70   BOBR4
2010-01-05   5.70   BOBR4
2010-01-06   5.70   BOBR4
2010-01-07   5.70   BOBR4
2010-01-08   5.70   BOBR4
...           ...     ...
2024-06-24   2.04   BOBR4
2024-06-25   2.02   BOBR4
2024-06-26   2.03   BOBR4
2024-06-27   2.03   BOBR4
2024-06-28   2.03   BOBR4

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04       NaN   BPAC5
2010-01-05       NaN   BPAC5
2010-01-06       NaN   BPAC5
2010-01-07       NaN   BPAC5
2010-01-08       NaN   BPAC5
...              ...     ...
2024-06-24  7.903537   BPAC5
2024-06-25  7.865032   BPAC5
2024-06-26  7.816897   BPAC5
2024-06-27  7.720631   BPAC5
2024-06-28  7.460709   BPAC5

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  8.585833   BPAN4
2010-01-05  8.957025   BPAN4
2010-01-06  9.150687   BPAN4
2010-01-07  9.392772   BPAN4
2010-01-08  9.521883   BPAN4
...              ...     ...
2024-06-24  7.850497   BPAN4
2024-06-25  7.869785   BPAN4
2024-06-26  7.898718   BPAN4
2024-06-27  7.956584   BPAN4
2024-06-28  7.802275   BPAN4

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   4.551799   BRAP4
2010-01-05   4.643529   BRAP4
2010-01-06   4.708555   BRAP4
2010-01-07   4.760808   BRAP4
2010-01-08   4.830480   BRAP4
...               ...     ...
2024-06-24  16.077465   BRAP4
2024-06-25  15.970580   BRAP4
2024-06-26  16.211075   BRAP4
2024-06-27  16.264515   BRAP4
2024-06-28  16.487196   BRAP4

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  19.426813   BRFS3
2010-01-05  19.630461   BRFS3
2010-01-06  19.897745   BRFS3
2010-01-07  19.774710   BRFS3
2010-01-08  19.855316   BRFS3
...               ...     ...
2024-06-24  20.640081   BRFS3
2024-06-25  20.709778   BRFS3
2024-06-26  21.008476   BRFS3
2024-06-27  21.954355   BRFS3
2024-06-28  22.571667   BRFS3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04   1.36385   BRGE7
2010-01-05   1.36385   BRGE7
2010-01-06   1.36385   BRGE7
2010-01-07   1.36385   BRGE7
2010-01-08   1.36385   BRGE7
...              ...     ...
2024-06-24  13.07000   BRGE7
2024-06-25  13.07000   BRGE7
2024-06-26  13.07000   BRGE7
2024-06-27  13.07000   BRGE7
2024-06-28  13.07000   BRGE7

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   BRIT3
2010-01-05    NaN   BRIT3
2010-01-06    NaN   BRIT3
2010-01-07    NaN   BRIT3
2010-01-08    NaN   BRIT3
...           ...     ...
2024-06-24    NaN   BRIT3
2024-06-25    NaN   BRIT3
2024-06-26    NaN   BRIT3
2024-06-27    NaN   BRIT3
2024-06-28    NaN   BRIT3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   7.362308   BRIV3
2010-01-05   7.291088   BRIV3
2010-01-06   7.299991   BRIV3
2010-01-07   7.291088   BRIV3
2010-01-08   7.210967   BRIV3
...               ...     ...
2024-06-24  12.860000   BRIV3
2024-06-25  12.860000   BRIV3
2024-06-26  12.860000   BRIV3
2024-06-27  12.860000   BRIV3
2024-06-28  12.860000   BRIV3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   9.049198   BRKM5
2010-01-05   8.966645   BRKM5
2010-01-06   9.182555   BRKM5
2010-01-07   8.953944   BRKM5
2010-01-08   8.826937   BRKM5
...               ...     ...
2024-06-24  17.990000   BRKM5
2024-06-25  18.010000   BRKM5
2024-06-26  17.850000   BRKM5
2024-06-27  18.440001   BRKM5
2024-06-28  17.860001   BRKM5

[3597 rows x 2 columns]

                 Close Empresa
Date
2010-01-04         NaN   BRPR3
2010-01-05         NaN   BRPR3
2010-01-06         NaN   BRPR3
2010-01-07         NaN   BRPR3
2010-01-08         NaN   BRPR3
...                ...     ...
2024-06-24  131.169998   BRPR3
2024-06-25  131.169998   BRPR3
2024-06-26  131.169998   BRPR3
2024-06-27  131.169998   BRPR3
2024-06-28  131.169998   BRPR3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   5.745832   BRSR6
2010-01-05   5.627768   BRSR6
2010-01-06   5.647447   BRSR6
2010-01-07   5.549057   BRSR6
2010-01-08   5.509701   BRSR6
...               ...     ...
2024-06-24  10.144218   BRSR6
2024-06-25  10.144218   BRSR6
2024-06-26  10.117045   BRSR6
2024-06-27  10.316307   BRSR6
2024-06-28  10.280078   BRSR6

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  1.808098   BSLI3
2010-01-05  1.825895   BSLI3
2010-01-06  1.910426   BSLI3
2010-01-07  1.863267   BSLI3
2010-01-08  1.881953   BSLI3
...              ...     ...
2024-06-24  9.177916   BSLI3
2024-06-25  9.375290   BSLI3
2024-06-26  9.375290   BSLI3
2024-06-27  9.089097   BSLI3
2024-06-28  9.375290   BSLI3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   6.409683   CALI3
2010-01-05   6.409683   CALI3
2010-01-06   6.409683   CALI3
2010-01-07   6.409683   CALI3
2010-01-08   6.409683   CALI3
...               ...     ...
2024-06-24  25.472258   CALI3
2024-06-25  25.472258   CALI3
2024-06-26  25.472258   CALI3
2024-06-27  25.472258   CALI3
2024-06-28  25.472258   CALI3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  84.495651   CAMB3
2010-01-05  84.495651   CAMB3
2010-01-06  84.495651   CAMB3
2010-01-07  84.495651   CAMB3
2010-01-08  84.495651   CAMB3
...               ...     ...
2024-06-24   9.893435   CAMB3
2024-06-25   9.587739   CAMB3
2024-06-26   9.624793   CAMB3
2024-06-27   9.819327   CAMB3
2024-06-28   9.745219   CAMB3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04       NaN   CAML3
2010-01-05       NaN   CAML3
2010-01-06       NaN   CAML3
2010-01-07       NaN   CAML3
2010-01-08       NaN   CAML3
...              ...     ...
2024-06-24  8.019347   CAML3
2024-06-25  8.142867   CAML3
2024-06-26  7.677289   CAML3
2024-06-27  7.838817   CAML3
2024-06-28  7.838817   CAML3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   CASH3
2010-01-05    NaN   CASH3
2010-01-06    NaN   CASH3
2010-01-07    NaN   CASH3
2010-01-08    NaN   CASH3
...           ...     ...
2024-06-24   5.69   CASH3
2024-06-25   5.58   CASH3
2024-06-26   5.65   CASH3
2024-06-27   5.84   CASH3
2024-06-28   5.85   CASH3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  4.133435   CASN3
2010-01-05  4.133435   CASN3
2010-01-06  4.133435   CASN3
2010-01-07  4.133435   CASN3
2010-01-08  4.133435   CASN3
...              ...     ...
2024-06-24  8.759628   CASN3
2024-06-25  8.759628   CASN3
2024-06-26  8.759628   CASN3
2024-06-27  8.759628   CASN3
2024-06-28  8.759628   CASN3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   CBAV3
2010-01-05    NaN   CBAV3
2010-01-06    NaN   CBAV3
2010-01-07    NaN   CBAV3
2010-01-08    NaN   CBAV3
...           ...     ...
2024-06-24   6.73   CBAV3
2024-06-25   6.69   CBAV3
2024-06-26   6.83   CBAV3
2024-06-27   6.79   CBAV3
2024-06-28   6.96   CBAV3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  36.360790   CBEE3
2010-01-05  36.099205   CBEE3
2010-01-06  35.576019   CBEE3
2010-01-07  35.837608   CBEE3
2010-01-08  36.099205   CBEE3
...               ...     ...
2024-06-24   8.896502   CBEE3
2024-06-25   8.896502   CBEE3
2024-06-26   8.896502   CBEE3
2024-06-27   9.525162   CBEE3
2024-06-28   9.239407   CBEE3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   CCRO3
2010-01-05    NaN   CCRO3
2010-01-06    NaN   CCRO3
2010-01-07    NaN   CCRO3
2010-01-08    NaN   CCRO3
...           ...     ...
2024-06-24    NaN   CCRO3
2024-06-25    NaN   CCRO3
2024-06-26    NaN   CCRO3
2024-06-27    NaN   CCRO3
2024-06-28    NaN   CCRO3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04       NaN   CEAB3
2010-01-05       NaN   CEAB3
2010-01-06       NaN   CEAB3
2010-01-07       NaN   CEAB3
2010-01-08       NaN   CEAB3
...              ...     ...
2024-06-24  9.667531   CEAB3
2024-06-25  9.514380   CEAB3
2024-06-26  9.121937   CEAB3
2024-06-27  9.399519   CEAB3
2024-06-28  8.940073   CEAB3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   0.981997   CEBR5
2010-01-05   0.981997   CEBR5
2010-01-06   0.981997   CEBR5
2010-01-07   0.981997   CEBR5
2010-01-08   0.981997   CEBR5
...               ...     ...
2024-06-24  16.411566   CEBR5
2024-06-25  16.411566   CEBR5
2024-06-26  16.348515   CEBR5
2024-06-27  16.249434   CEBR5
2024-06-28  16.438589   CEBR5

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   9.870531   CEDO3
2010-01-05   9.870531   CEDO3
2010-01-06  10.102289   CEDO3
2010-01-07  10.102289   CEDO3
2010-01-08  10.102289   CEDO3
...               ...     ...
2024-06-24  26.780001   CEDO3
2024-06-25  26.780001   CEDO3
2024-06-26  26.780001   CEDO3
2024-06-27  26.780001   CEDO3
2024-06-28  26.750000   CEDO3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  11.267422   CEEB5
2010-01-05  11.267422   CEEB5
2010-01-06  11.267422   CEEB5
2010-01-07  11.267422   CEEB5
2010-01-08  11.267422   CEEB5
...               ...     ...
2024-06-24  36.896355   CEEB5
2024-06-25  36.896355   CEEB5
2024-06-26  37.168163   CEEB5
2024-06-27  37.168163   CEEB5
2024-06-28  37.168163   CEEB5

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   CEED4
2010-01-05    NaN   CEED4
2010-01-06    NaN   CEED4
2010-01-07    NaN   CEED4
2010-01-08    NaN   CEED4
...           ...     ...
2024-06-24   25.0   CEED4
2024-06-25   25.0   CEED4
2024-06-26   25.0   CEED4
2024-06-27   25.0   CEED4
2024-06-28   25.0   CEED4

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   5.397418   CEGR3
2010-01-05   5.397418   CEGR3
2010-01-06   5.397418   CEGR3
2010-01-07   5.397418   CEGR3
2010-01-08   5.397418   CEGR3
...               ...     ...
2024-06-24  67.444328   CEGR3
2024-06-25  67.444328   CEGR3
2024-06-26  67.444328   CEGR3
2024-06-27  67.444328   CEGR3
2024-06-28  67.444328   CEGR3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   7.614817   CGAS3
2010-01-05   7.612319   CGAS3
2010-01-06   7.614817   CGAS3
2010-01-07   7.702226   CGAS3
2010-01-08   7.617313   CGAS3
...               ...     ...
2024-06-24  96.903748   CGAS3
2024-06-25  96.903748   CGAS3
2024-06-26  96.903748   CGAS3
2024-06-27  96.903748   CGAS3
2024-06-28  96.848404   CGAS3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   4.806808   CGRA4
2010-01-05   4.806808   CGRA4
2010-01-06   4.806808   CGRA4
2010-01-07   4.806808   CGRA4
2010-01-08   4.806808   CGRA4
...               ...     ...
2024-06-24  23.122154   CGRA4
2024-06-25  22.732977   CGRA4
2024-06-26  22.221361   CGRA4
2024-06-27  22.825781   CGRA4
2024-06-28  22.488016   CGRA4

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   CIEL3
2010-01-05    NaN   CIEL3
2010-01-06    NaN   CIEL3
2010-01-07    NaN   CIEL3
2010-01-08    NaN   CIEL3
...           ...     ...
2024-06-24    NaN   CIEL3
2024-06-25    NaN   CIEL3
2024-06-26    NaN   CIEL3
2024-06-27    NaN   CIEL3
2024-06-28    NaN   CIEL3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   CLSA3
2010-01-05    NaN   CLSA3
2010-01-06    NaN   CLSA3
2010-01-07    NaN   CLSA3
2010-01-08    NaN   CLSA3
...           ...     ...
2024-06-24    NaN   CLSA3
2024-06-25    NaN   CLSA3
2024-06-26    NaN   CLSA3
2024-06-27    NaN   CLSA3
2024-06-28    NaN   CLSA3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04        NaN   CLSC4
2010-01-05        NaN   CLSC4
2010-01-06        NaN   CLSC4
2010-01-07        NaN   CLSC4
2010-01-08        NaN   CLSC4
...               ...     ...
2024-06-24  63.356476   CLSC4
2024-06-25  62.537098   CLSC4
2024-06-26  62.537098   CLSC4
2024-06-27  63.127243   CLSC4
2024-06-28  64.891220   CLSC4

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  1.939728   CMIG4
2010-01-05  1.969408   CMIG4
2010-01-06  1.932310   CMIG4
2010-01-07  1.913759   CMIG4
2010-01-08  1.911902   CMIG4
...              ...     ...
2024-06-24  8.968081   CMIG4
2024-06-25  8.968081   CMIG4
2024-06-26  8.814634   CMIG4
2024-06-27  8.558890   CMIG4
2024-06-28  8.431019   CMIG4

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04       NaN   CMIN3
2010-01-05       NaN   CMIN3
2010-01-06       NaN   CMIN3
2010-01-07       NaN   CMIN3
2010-01-08       NaN   CMIN3
...              ...     ...
2024-06-24  4.574463   CMIN3
2024-06-25  4.494985   CMIN3
2024-06-26  4.565632   CMIN3
2024-06-27  4.547970   CMIN3
2024-06-28  4.583294   CMIN3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  14.819014   COCE5
2010-01-05  15.014737   COCE5
2010-01-06  14.996097   COCE5
2010-01-07  14.856295   COCE5
2010-01-08  14.907556   COCE5
...               ...     ...
2024-06-24  29.381050   COCE5
2024-06-25  28.433273   COCE5
2024-06-26  27.978342   COCE5
2024-06-27  28.423796   COCE5
2024-06-28  29.001940   COCE5

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04       NaN   COGN3
2010-01-05       NaN   COGN3
2010-01-06       NaN   COGN3
2010-01-07       NaN   COGN3
2010-01-08       NaN   COGN3
...              ...     ...
2024-06-24  1.733059   COGN3
2024-06-25  1.723322   COGN3
2024-06-26  1.723322   COGN3
2024-06-27  1.830421   COGN3
2024-06-28  1.723322   COGN3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   0.959117   CORR4
2010-01-05   0.959117   CORR4
2010-01-06   0.959117   CORR4
2010-01-07   0.959117   CORR4
2010-01-08   0.959117   CORR4
...               ...     ...
2024-06-24  82.000000   CORR4
2024-06-25  82.000000   CORR4
2024-06-26  82.000000   CORR4
2024-06-27  82.000000   CORR4
2024-06-28  82.000000   CORR4

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   8.546406   CPFE3
2010-01-05   8.443381   CPFE3
2010-01-06   8.499577   CPFE3
2010-01-07   8.394210   CPFE3
2010-01-08   8.499577   CPFE3
...               ...     ...
2024-06-24  32.689999   CPFE3
2024-06-25  32.630001   CPFE3
2024-06-26  32.520000   CPFE3
2024-06-27  33.130001   CPFE3
2024-06-28  32.730000   CPFE3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  1.707214   CPLE6
2010-01-05  1.709445   CPLE6
2010-01-06  1.717033   CPLE6
2010-01-07  1.700519   CPLE6
2010-01-08  1.707214   CPLE6
...              ...     ...
2024-06-24  8.911486   CPLE6
2024-06-25  8.853743   CPLE6
2024-06-26  8.921108   CPLE6
2024-06-27  9.103957   CPLE6
2024-06-28  8.949980   CPLE6

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   CRFB3
2010-01-05    NaN   CRFB3
2010-01-06    NaN   CRFB3
2010-01-07    NaN   CRFB3
2010-01-08    NaN   CRFB3
...           ...     ...
2024-06-24   9.00   CRFB3
2024-06-25   8.95   CRFB3
2024-06-26   8.79   CRFB3
2024-06-27   9.16   CRFB3
2024-06-28   9.02   CRFB3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  3.695351   CRIV3
2010-01-05  3.695351   CRIV3
2010-01-06  3.686553   CRIV3
2010-01-07  3.686553   CRIV3
2010-01-08  3.695351   CRIV3
...              ...     ...
2024-06-24  6.980000   CRIV3
2024-06-25  6.980000   CRIV3
2024-06-26  6.980000   CRIV3
2024-06-27  6.980000   CRIV3
2024-06-28  6.980000   CRIV3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   4.978762   CRPG5
2010-01-05   4.267511   CRPG5
2010-01-06   4.267511   CRPG5
2010-01-07   4.623137   CRPG5
2010-01-08   4.623137   CRPG5
...               ...     ...
2024-06-24  29.629999   CRPG5
2024-06-25  29.200001   CRPG5
2024-06-26  29.299999   CRPG5
2024-06-27  29.219999   CRPG5
2024-06-28  29.410000   CRPG5

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   3.731021   CSAN3
2010-01-05   3.732484   CSAN3
2010-01-06   3.625674   CSAN3
2010-01-07   3.432540   CSAN3
2010-01-08   3.463265   CSAN3
...               ...     ...
2024-06-24  13.200000   CSAN3
2024-06-25  13.180000   CSAN3
2024-06-26  13.390000   CSAN3
2024-06-27  13.770000   CSAN3
2024-06-28  13.540000   CSAN3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04       NaN   CSED3
2010-01-05       NaN   CSED3
2010-01-06       NaN   CSED3
2010-01-07       NaN   CSED3
2010-01-08       NaN   CSED3
...              ...     ...
2024-06-24  3.517979   CSED3
2024-06-25  3.427075   CSED3
2024-06-26  3.327081   CSED3
2024-06-27  3.527070   CSED3
2024-06-28  3.408895   CSED3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   5.094426   CSMG3
2010-01-05   5.094426   CSMG3
2010-01-06   5.094426   CSMG3
2010-01-07   4.785674   CSMG3
2010-01-08   4.586527   CSMG3
...               ...     ...
2024-06-24  19.650988   CSMG3
2024-06-25  19.760921   CSMG3
2024-06-26  19.345570   CSMG3
2024-06-27  19.373556   CSMG3
2024-06-28  19.485487   CSMG3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  12.686666   CSNA3
2010-01-05  12.804029   CSNA3
2010-01-06  12.819828   CSNA3
2010-01-07  12.684407   CSNA3
2010-01-08  12.971047   CSNA3
...               ...     ...
2024-06-24  12.099466   CSNA3
2024-06-25  11.966191   CSNA3
2024-06-26  11.937633   CSNA3
2024-06-27  12.280339   CSNA3
2024-06-28  12.289859   CSNA3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   CSRN3
2010-01-05    NaN   CSRN3
2010-01-06    NaN   CSRN3
2010-01-07    NaN   CSRN3
2010-01-08    NaN   CSRN3
...           ...     ...
2024-06-24    NaN   CSRN3
2024-06-25    NaN   CSRN3
2024-06-26    NaN   CSRN3
2024-06-27    NaN   CSRN3
2024-06-28    NaN   CSRN3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   4.909963   CSUD3
2010-01-05   4.997348   CSUD3
2010-01-06   4.964580   CSUD3
2010-01-07   5.024656   CSUD3
2010-01-08   5.019194   CSUD3
...               ...     ...
2024-06-24  17.058062   CSUD3
2024-06-25  16.909563   CSUD3
2024-06-26  17.002373   CSUD3
2024-06-27  17.308640   CSUD3
2024-06-28  17.271519   CSUD3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  40.797871   CTKA4
2010-01-05  40.797871   CTKA4
2010-01-06  39.437939   CTKA4
2010-01-07  39.340801   CTKA4
2010-01-08  40.700733   CTKA4
...               ...     ...
2024-06-24  17.000000   CTKA4
2024-06-25  17.000000   CTKA4
2024-06-26  17.000000   CTKA4
2024-06-27  17.000000   CTKA4
2024-06-28  16.500000   CTKA4

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  20.972668   CTNM4
2010-01-05  21.452044   CTNM4
2010-01-06  21.571888   CTNM4
2010-01-07  22.530638   CTNM4
2010-01-08  23.169806   CTNM4
...               ...     ...
2024-06-24   0.700000   CTNM4
2024-06-25   0.680000   CTNM4
2024-06-26   0.660000   CTNM4
2024-06-27   0.630000   CTNM4
2024-06-28   0.620000   CTNM4

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  12.568857   CTSA4
2010-01-05  12.568857   CTSA4
2010-01-06  12.911644   CTSA4
2010-01-07  13.254432   CTSA4
2010-01-08  13.254432   CTSA4
...               ...     ...
2024-06-24   3.400000   CTSA4
2024-06-25   3.200000   CTSA4
2024-06-26   3.200000   CTSA4
2024-06-27   3.280000   CTSA4
2024-06-28   3.280000   CTSA4

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04        NaN   CURY3
2010-01-05        NaN   CURY3
2010-01-06        NaN   CURY3
2010-01-07        NaN   CURY3
2010-01-08        NaN   CURY3
...               ...     ...
2024-06-24  18.517946   CURY3
2024-06-25  19.175945   CURY3
2024-06-26  19.476742   CURY3
2024-06-27  19.448544   CURY3
2024-06-28  19.363943   CURY3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   CVCB3
2010-01-05    NaN   CVCB3
2010-01-06    NaN   CVCB3
2010-01-07    NaN   CVCB3
2010-01-08    NaN   CVCB3
...           ...     ...
2024-06-24   1.97   CVCB3
2024-06-25   1.92   CVCB3
2024-06-26   1.90   CVCB3
2024-06-27   2.01   CVCB3
2024-06-28   1.96   CVCB3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04        NaN   CXSE3
2010-01-05        NaN   CXSE3
2010-01-06        NaN   CXSE3
2010-01-07        NaN   CXSE3
2010-01-08        NaN   CXSE3
...               ...     ...
2024-06-24  13.187963   CXSE3
2024-06-25  13.132399   CXSE3
2024-06-26  13.132399   CXSE3
2024-06-27  13.243531   CXSE3
2024-06-28  13.252794   CXSE3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  15.225354   CYRE3
2010-01-05  15.080644   CYRE3
2010-01-06  15.099525   CYRE3
2010-01-07  14.810118   CYRE3
2010-01-08  14.784952   CYRE3
...               ...     ...
2024-06-24  19.510000   CYRE3
2024-06-25  19.559999   CYRE3
2024-06-26  19.080000   CYRE3
2024-06-27  19.500000   CYRE3
2024-06-28  18.850000   CYRE3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  13.158499   DASA3
2010-01-05  13.263692   DASA3
2010-01-06  12.954969   DASA3
2010-01-07  13.009851   DASA3
2010-01-08  13.080744   DASA3
...               ...     ...
2024-06-24   3.050000   DASA3
2024-06-25   2.920000   DASA3
2024-06-26   2.680000   DASA3
2024-06-27   2.840000   DASA3
2024-06-28   2.770000   DASA3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04        NaN   DESK3
2010-01-05        NaN   DESK3
2010-01-06        NaN   DESK3
2010-01-07        NaN   DESK3
2010-01-08        NaN   DESK3
...               ...     ...
2024-06-24  14.792236   DESK3
2024-06-25  14.941652   DESK3
2024-06-26  14.583053   DESK3
2024-06-27  15.619007   DESK3
2024-06-28  15.240485   DESK3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04       NaN   DEXP4
2010-01-05       NaN   DEXP4
2010-01-06       NaN   DEXP4
2010-01-07       NaN   DEXP4
2010-01-08       NaN   DEXP4
...              ...     ...
2024-06-24  9.433467   DEXP4
2024-06-25  9.433467   DEXP4
2024-06-26  9.528754   DEXP4
2024-06-27  9.757444   DEXP4
2024-06-28  9.776503   DEXP4

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   4.867410   DIRR3
2010-01-05   4.846154   DIRR3
2010-01-06   4.803645   DIRR3
2010-01-07   4.846154   DIRR3
2010-01-08   4.854657   DIRR3
...               ...     ...
2024-06-24  21.811123   DIRR3
2024-06-25  22.182953   DIRR3
2024-06-26  22.554781   DIRR3
2024-06-27  22.664637   DIRR3
2024-06-28  22.470274   DIRR3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   DMFN3
2010-01-05    NaN   DMFN3
2010-01-06    NaN   DMFN3
2010-01-07    NaN   DMFN3
2010-01-08    NaN   DMFN3
...           ...     ...
2024-06-24    NaN   DMFN3
2024-06-25    NaN   DMFN3
2024-06-26    NaN   DMFN3
2024-06-27    NaN   DMFN3
2024-06-28    NaN   DMFN3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   DMVF3
2010-01-05    NaN   DMVF3
2010-01-06    NaN   DMVF3
2010-01-07    NaN   DMVF3
2010-01-08    NaN   DMVF3
...           ...     ...
2024-06-24   7.23   DMVF3
2024-06-25   7.38   DMVF3
2024-06-26   7.33   DMVF3
2024-06-27   7.30   DMVF3
2024-06-28   7.28   DMVF3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  1.146775   DOHL4
2010-01-05  1.146775   DOHL4
2010-01-06  1.146775   DOHL4
2010-01-07  1.146775   DOHL4
2010-01-08  1.146775   DOHL4
...              ...     ...
2024-06-24  4.038835   DOHL4
2024-06-25  3.979000   DOHL4
2024-06-26  3.988972   DOHL4
2024-06-27  3.979000   DOHL4
2024-06-28  3.979000   DOHL4

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   DOTZ3
2010-01-05    NaN   DOTZ3
2010-01-06    NaN   DOTZ3
2010-01-07    NaN   DOTZ3
2010-01-08    NaN   DOTZ3
...           ...     ...
2024-06-24   6.84   DOTZ3
2024-06-25   6.84   DOTZ3
2024-06-26   6.99   DOTZ3
2024-06-27   6.80   DOTZ3
2024-06-28   6.32   DOTZ3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  5.920577   DTCY3
2010-01-05  6.008943   DTCY3
2010-01-06  5.920577   DTCY3
2010-01-07  5.920577   DTCY3
2010-01-08  5.832210   DTCY3
...              ...     ...
2024-06-24  5.700000   DTCY3
2024-06-25  6.280000   DTCY3
2024-06-26  6.280000   DTCY3
2024-06-27  6.280000   DTCY3
2024-06-28  6.280000   DTCY3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  5.941545   DXCO3
2010-01-05  6.208108   DXCO3
2010-01-06  6.379972   DXCO3
2010-01-07  6.348405   DXCO3
2010-01-08  6.362436   DXCO3
...              ...     ...
2024-06-24  6.631203   DXCO3
2024-06-25  6.522170   DXCO3
2024-06-26  6.532082   DXCO3
2024-06-27  6.740236   DXCO3
2024-06-28  6.502345   DXCO3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   2.170857   EALT4
2010-01-05   2.093556   EALT4
2010-01-06   2.090336   EALT4
2010-01-07   2.099998   EALT4
2010-01-08   2.099998   EALT4
...               ...     ...
2024-06-24  11.190000   EALT4
2024-06-25  11.060000   EALT4
2024-06-26  11.170000   EALT4
2024-06-27  11.100000   EALT4
2024-06-28  11.200000   EALT4

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   ECOR3
2010-01-05    NaN   ECOR3
2010-01-06    NaN   ECOR3
2010-01-07    NaN   ECOR3
2010-01-08    NaN   ECOR3
...           ...     ...
2024-06-24   6.79   ECOR3
2024-06-25   6.87   ECOR3
2024-06-26   6.65   ECOR3
2024-06-27   6.90   ECOR3
2024-06-28   6.60   ECOR3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   9.559612   ECPR3
2010-01-05   9.559612   ECPR3
2010-01-06   9.559612   ECPR3
2010-01-07   9.559612   ECPR3
2010-01-08   9.559612   ECPR3
...               ...     ...
2024-06-24  90.250000   ECPR3
2024-06-25  90.250000   ECPR3
2024-06-26  90.250000   ECPR3
2024-06-27  90.250000   ECPR3
2024-06-28  90.250000   ECPR3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   7.624839   EGIE3
2010-01-05   7.684906   EGIE3
2010-01-06   7.607175   EGIE3
2010-01-07   7.656640   EGIE3
2010-01-08   7.593040   EGIE3
...               ...     ...
2024-06-24  42.101601   EGIE3
2024-06-25  41.779705   EGIE3
2024-06-26  41.940651   EGIE3
2024-06-27  42.035332   EGIE3
2024-06-28  41.931187   EGIE3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   5.066833   EKTR4
2010-01-05   5.066833   EKTR4
2010-01-06   5.066833   EKTR4
2010-01-07   5.066833   EKTR4
2010-01-08   5.066833   EKTR4
...               ...     ...
2024-06-24  35.002365   EKTR4
2024-06-25  35.092121   EKTR4
2024-06-26  35.607277   EKTR4
2024-06-27  35.607277   EKTR4
2024-06-28  35.607277   EKTR4

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  21.190763   ELET3
2010-01-05  21.016928   ELET3
2010-01-06  20.747768   ELET3
2010-01-07  21.230011   ELET3
2010-01-08  21.588890   ELET3
...               ...     ...
2024-06-24  33.431496   ELET3
2024-06-25  33.278622   ELET3
2024-06-26  33.106636   ELET3
2024-06-27  34.071648   ELET3
2024-06-28  34.253185   ELET3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   ELMD3
2010-01-05    NaN   ELMD3
2010-01-06    NaN   ELMD3
2010-01-07    NaN   ELMD3
2010-01-08    NaN   ELMD3
...           ...     ...
2024-06-24    NaN   ELMD3
2024-06-25    NaN   ELMD3
2024-06-26    NaN   ELMD3
2024-06-27    NaN   ELMD3
2024-06-28    NaN   ELMD3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   8.343370   EMAE4
2010-01-05   8.403396   EMAE4
2010-01-06   8.535447   EMAE4
2010-01-07   8.523444   EMAE4
2010-01-08   8.241330   EMAE4
...               ...     ...
2024-06-24  46.324947   EMAE4
2024-06-25  46.609634   EMAE4
2024-06-26  46.619453   EMAE4
2024-06-27  46.099163   EMAE4
2024-06-28  46.717617   EMAE4

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   8.916506   EMBR3
2010-01-05   8.708725   EMBR3
2010-01-06   8.672588   EMBR3
2010-01-07   8.555148   EMBR3
2010-01-08   8.537080   EMBR3
...               ...     ...
2024-06-24  37.480000   EMBR3
2024-06-25  37.750000   EMBR3
2024-06-26  38.020000   EMBR3
2024-06-27  38.220001   EMBR3
2024-06-28  36.150002   EMBR3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   ENAT3
2010-01-05    NaN   ENAT3
2010-01-06    NaN   ENAT3
2010-01-07    NaN   ENAT3
2010-01-08    NaN   ENAT3
...           ...     ...
2024-06-24    NaN   ENAT3
2024-06-25    NaN   ENAT3
2024-06-26    NaN   ENAT3
2024-06-27    NaN   ENAT3
2024-06-28    NaN   ENAT3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  84.674973   ENEV3
2010-01-05  83.496887   ENEV3
2010-01-06  84.490898   ENEV3
2010-01-07  87.620186   ENEV3
2010-01-08  88.577385   ENEV3
...               ...     ...
2024-06-24  12.500000   ENEV3
2024-06-25  12.610000   ENEV3
2024-06-26  12.780000   ENEV3
2024-06-27  13.160000   ENEV3
2024-06-28  12.700000   ENEV3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   1.147982   ENGI3
2010-01-05   1.013534   ENGI3
2010-01-06   1.127298   ENGI3
2010-01-07   1.127298   ENGI3
2010-01-08   1.127298   ENGI3
...               ...     ...
2024-06-24  13.007539   ENGI3
2024-06-25  12.864284   ENGI3
2024-06-26  12.749680   ENGI3
2024-06-27  13.045740   ENGI3
2024-06-28  13.867068   ENGI3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   ENJU3
2010-01-05    NaN   ENJU3
2010-01-06    NaN   ENJU3
2010-01-07    NaN   ENJU3
2010-01-08    NaN   ENJU3
...           ...     ...
2024-06-24   2.10   ENJU3
2024-06-25   2.06   ENJU3
2024-06-26   2.12   ENJU3
2024-06-27   2.09   ENJU3
2024-06-28   1.99   ENJU3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   4.123268   ENMT3
2010-01-05   4.123268   ENMT3
2010-01-06   4.123268   ENMT3
2010-01-07   4.123268   ENMT3
2010-01-08   4.123268   ENMT3
...               ...     ...
2024-06-24  80.343811   ENMT3
2024-06-25  80.343811   ENMT3
2024-06-26  80.343811   ENMT3
2024-06-27  80.343811   ENMT3
2024-06-28  80.343811   ENMT3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  7.903302   EPAR3
2010-01-05  8.017842   EPAR3
2010-01-06  7.788762   EPAR3
2010-01-07  7.903302   EPAR3
2010-01-08  7.674221   EPAR3
...              ...     ...
2024-06-24  4.371300   EPAR3
2024-06-25  4.371300   EPAR3
2024-06-26  4.385046   EPAR3
2024-06-27  4.330060   EPAR3
2024-06-28  4.330060   EPAR3

[3597 rows x 2 columns]

                  Close Empresa
Date
2010-01-04  1599.962402   EQPA3
2010-01-05  1599.962402   EQPA3
2010-01-06  1599.962402   EQPA3
2010-01-07  1599.962402   EQPA3
2010-01-08  1599.962402   EQPA3
...                 ...     ...
2024-06-24     6.074306   EQPA3
2024-06-25     6.208892   EQPA3
2024-06-26     6.298615   EQPA3
2024-06-27     6.074306   EQPA3
2024-06-28     6.181974   EQPA3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   3.345943   EQTL3
2010-01-05   3.372334   EQTL3
2010-01-06   3.336519   EQTL3
2010-01-07   3.298817   EQTL3
2010-01-08   3.347828   EQTL3
...               ...     ...
2024-06-24  29.652288   EQTL3
2024-06-25  29.114061   EQTL3
2024-06-26  29.004425   EQTL3
2024-06-27  30.828415   EQTL3
2024-06-28  30.589203   EQTL3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04       NaN   ESPA3
2010-01-05       NaN   ESPA3
2010-01-06       NaN   ESPA3
2010-01-07       NaN   ESPA3
2010-01-08       NaN   ESPA3
...              ...     ...
2024-06-24  1.027917   ESPA3
2024-06-25  1.037897   ESPA3
2024-06-26  1.007958   ESPA3
2024-06-27  0.997978   ESPA3
2024-06-28  1.017938   ESPA3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04   1.38   ESTR4
2010-01-05   1.40   ESTR4
2010-01-06   1.44   ESTR4
2010-01-07   1.40   ESTR4
2010-01-08   1.46   ESTR4
...           ...     ...
2024-06-24   1.84   ESTR4
2024-06-25   1.84   ESTR4
2024-06-26   1.84   ESTR4
2024-06-27   1.84   ESTR4
2024-06-28   1.84   ESTR4

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  12.043159   ETER3
2010-01-05  12.014822   ETER3
2010-01-06  12.014822   ETER3
2010-01-07  12.057329   ETER3
2010-01-08  12.369031   ETER3
...               ...     ...
2024-06-24   5.843115   ETER3
2024-06-25   5.677007   ETER3
2024-06-26   5.628152   ETER3
2024-06-27   5.921284   ETER3
2024-06-28   5.774718   ETER3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   3.687025   EUCA4
2010-01-05   3.621054   EUCA4
2010-01-06   3.635715   EUCA4
2010-01-07   3.877607   EUCA4
2010-01-08   3.767656   EUCA4
...               ...     ...
2024-06-24  14.026835   EUCA4
2024-06-25  14.197087   EUCA4
2024-06-26  14.111961   EUCA4
2024-06-27  14.632174   EUCA4
2024-06-28  14.178170   EUCA4

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  5.236392   EVEN3
2010-01-05  5.129141   EVEN3
2010-01-06  5.072361   EVEN3
2010-01-07  4.996655   EVEN3
2010-01-08  4.908330   EVEN3
...              ...     ...
2024-06-24  6.308888   EVEN3
2024-06-25  6.271111   EVEN3
2024-06-26  6.091666   EVEN3
2024-06-27  6.186111   EVEN3
2024-06-28  6.186111   EVEN3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   3.400902   EZTC3
2010-01-05   3.467739   EZTC3
2010-01-06   3.444149   EZTC3
2010-01-07   3.436286   EZTC3
2010-01-08   3.459877   EZTC3
...               ...     ...
2024-06-24  12.280795   EZTC3
2024-06-25  12.363961   EZTC3
2024-06-26  12.049780   EZTC3
2024-06-27  12.179148   EZTC3
2024-06-28  11.957372   EZTC3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  1.255625   FESA4
2010-01-05  1.234513   FESA4
2010-01-06  1.261182   FESA4
2010-01-07  1.310073   FESA4
2010-01-08  1.355631   FESA4
...              ...     ...
2024-06-24  7.377703   FESA4
2024-06-25  7.302613   FESA4
2024-06-26  7.480953   FESA4
2024-06-27  7.696841   FESA4
2024-06-28  7.574817   FESA4

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04  10.80   FHER3
2010-01-05  10.60   FHER3
2010-01-06  10.70   FHER3
2010-01-07  11.67   FHER3
2010-01-08  11.61   FHER3
...           ...     ...
2024-06-24   3.77   FHER3
2024-06-25   3.75   FHER3
2024-06-26   3.75   FHER3
2024-06-27   3.75   FHER3
2024-06-28   3.79   FHER3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  91.424683   FIEI3
2010-01-05  91.424683   FIEI3
2010-01-06  91.424683   FIEI3
2010-01-07  91.134453   FIEI3
2010-01-08  90.699089   FIEI3
...               ...     ...
2024-06-24  10.000000   FIEI3
2024-06-25  10.000000   FIEI3
2024-06-26  10.000000   FIEI3
2024-06-27  10.500000   FIEI3
2024-06-28  10.500000   FIEI3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  16.285130   FIGE4
2010-01-05  16.285130   FIGE4
2010-01-06  16.285130   FIGE4
2010-01-07  16.285130   FIGE4
2010-01-08  16.285130   FIGE4
...               ...     ...
2024-06-24  37.962315   FIGE4
2024-06-25  37.962315   FIGE4
2024-06-26  37.962315   FIGE4
2024-06-27  37.962315   FIGE4
2024-06-28  37.962315   FIGE4

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04       NaN   FIQE3
2010-01-05       NaN   FIQE3
2010-01-06       NaN   FIQE3
2010-01-07       NaN   FIQE3
2010-01-08       NaN   FIQE3
...              ...     ...
2024-06-24  3.244852   FIQE3
2024-06-25  3.303143   FIQE3
2024-06-26  3.342003   FIQE3
2024-06-27  3.351719   FIQE3
2024-06-28  3.351719   FIQE3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   4.896065   FLRY3
2010-01-05   4.869017   FLRY3
2010-01-06   5.044841   FLRY3
2010-01-07   5.061070   FLRY3
2010-01-08   5.163862   FLRY3
...               ...     ...
2024-06-24  13.270341   FLRY3
2024-06-25  13.335029   FLRY3
2024-06-26  13.307304   FLRY3
2024-06-27  13.787846   FLRY3
2024-06-28  13.889500   FLRY3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   1.640372   FRAS3
2010-01-05   1.640372   FRAS3
2010-01-06   1.640372   FRAS3
2010-01-07   1.640372   FRAS3
2010-01-08   1.640372   FRAS3
...               ...     ...
2024-06-24  17.296074   FRAS3
2024-06-25  18.432453   FRAS3
2024-06-26  18.509497   FRAS3
2024-06-27  18.730993   FRAS3
2024-06-28  18.673210   FRAS3

[3597 rows x 2 columns]

                 Close Empresa
Date
2010-01-04  292.259216   FRIO3
2010-01-05  310.507050   FRIO3
2010-01-06  344.353790   FRIO3
2010-01-07  356.126556   FRIO3
2010-01-08  362.012970   FRIO3
...                ...     ...
2024-06-24  280.000000   FRIO3
2024-06-25  300.000000   FRIO3
2024-06-26  300.000000   FRIO3
2024-06-27  330.000000   FRIO3
2024-06-28  350.000000   FRIO3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   7.971799   GEPA3
2010-01-05   7.971799   GEPA3
2010-01-06   7.971799   GEPA3
2010-01-07   7.971799   GEPA3
2010-01-08   7.971799   GEPA3
...               ...     ...
2024-06-24  20.481823   GEPA3
2024-06-25  20.481823   GEPA3
2024-06-26  20.481823   GEPA3
2024-06-27  20.481823   GEPA3
2024-06-28  20.481823   GEPA3

[3597 rows x 2 columns]

                   Close Empresa
Date
2010-01-04  13416.837891   GFSA3
2010-01-05  13199.620117   GFSA3
2010-01-06  13221.341797   GFSA3
2010-01-07  12982.401367   GFSA3
2010-01-08  12692.777344   GFSA3
...                  ...     ...
2024-06-24     71.000000   GFSA3
2024-06-25     68.000000   GFSA3
2024-06-26     67.400002   GFSA3
2024-06-27     68.000000   GFSA3
2024-06-28     66.800003   GFSA3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  13.532270   GGBR4
2010-01-05  13.760859   GGBR4
2010-01-06  13.852291   GGBR4
2010-01-07  13.541419   GGBR4
2010-01-08  13.504844   GGBR4
...               ...     ...
2024-06-24  17.216366   GGBR4
2024-06-25  17.206722   GGBR4
2024-06-26  17.563585   GGBR4
2024-06-27  17.611811   GGBR4
2024-06-28  17.727551   GGBR4

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04        NaN   GGPS3
2010-01-05        NaN   GGPS3
2010-01-06        NaN   GGPS3
2010-01-07        NaN   GGPS3
2010-01-08        NaN   GGPS3
...               ...     ...
2024-06-24  17.003550   GGPS3
2024-06-25  17.180365   GGPS3
2024-06-26  17.180365   GGPS3
2024-06-27  17.386646   GGPS3
2024-06-28  16.934790   GGPS3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04       NaN   GMAT3
2010-01-05       NaN   GMAT3
2010-01-06       NaN   GMAT3
2010-01-07       NaN   GMAT3
2010-01-08       NaN   GMAT3
...              ...     ...
2024-06-24  6.896046   GMAT3
2024-06-25  6.886333   GMAT3
2024-06-26  6.760067   GMAT3
2024-06-27  6.954322   GMAT3
2024-06-28  6.730929   GMAT3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  18.371168   GOAU4
2010-01-05  18.592016   GOAU4
2010-01-06  18.776918   GOAU4
2010-01-07  18.407125   GOAU4
2010-01-08  18.437943   GOAU4
...               ...     ...
2024-06-24  10.044009   GOAU4
2024-06-25  10.044009   GOAU4
2024-06-26  10.159903   GOAU4
2024-06-27  10.266136   GOAU4
2024-06-28  10.285452   GOAU4

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  26.299999   GOLL4
2010-01-05  26.080000   GOLL4
2010-01-06  26.379999   GOLL4
2010-01-07  26.660000   GOLL4
2010-01-08  27.950001   GOLL4
...               ...     ...
2024-06-24   1.040000   GOLL4
2024-06-25   1.020000   GOLL4
2024-06-26   0.980000   GOLL4
2024-06-27   1.000000   GOLL4
2024-06-28   1.030000   GOLL4

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   6.955682   GPAR3
2010-01-05   6.955682   GPAR3
2010-01-06   6.955682   GPAR3
2010-01-07   6.955682   GPAR3
2010-01-08   6.955682   GPAR3
...               ...     ...
2024-06-24  47.500000   GPAR3
2024-06-25  47.500000   GPAR3
2024-06-26  47.500000   GPAR3
2024-06-27  47.500000   GPAR3
2024-06-28  47.500000   GPAR3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  1.449149   GRND3
2010-01-05  1.471558   GRND3
2010-01-06  1.482016   GRND3
2010-01-07  1.461101   GRND3
2010-01-08  1.461101   GRND3
...              ...     ...
2024-06-24  5.466476   GRND3
2024-06-25  5.411537   GRND3
2024-06-26  5.283345   GRND3
2024-06-27  5.338284   GRND3
2024-06-28  5.274188   GRND3

[3597 rows x 2 columns]

                 Close Empresa
Date
2010-01-04  180.567917   GSHP3
2010-01-05  182.830154   GSHP3
2010-01-06  186.120682   GSHP3
2010-01-07  185.298035   GSHP3
2010-01-08  191.262146   GSHP3
...                ...     ...
2024-06-24   10.500000   GSHP3
2024-06-25   10.500000   GSHP3
2024-06-26   10.500000   GSHP3
2024-06-27   10.500000   GSHP3
2024-06-28   10.500000   GSHP3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  6.321063   GUAR3
2010-01-05  6.569895   GUAR3
2010-01-06  6.560048   GUAR3
2010-01-07  6.353286   GUAR3
2010-01-08  6.292421   GUAR3
...              ...     ...
2024-06-24  6.680000   GUAR3
2024-06-25  6.520000   GUAR3
2024-06-26  6.430000   GUAR3
2024-06-27  6.950000   GUAR3
2024-06-28  6.960000   GUAR3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04   2.73   HAGA4
2010-01-05   2.71   HAGA4
2010-01-06   2.70   HAGA4
2010-01-07   2.70   HAGA4
2010-01-08   2.93   HAGA4
...           ...     ...
2024-06-24   1.21   HAGA4
2024-06-25   1.18   HAGA4
2024-06-26   1.15   HAGA4
2024-06-27   1.17   HAGA4
2024-06-28   1.14   HAGA4

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04        NaN   HAPV3
2010-01-05        NaN   HAPV3
2010-01-06        NaN   HAPV3
2010-01-07        NaN   HAPV3
2010-01-08        NaN   HAPV3
...               ...     ...
2024-06-24  58.349998   HAPV3
2024-06-25  57.450001   HAPV3
2024-06-26  57.149998   HAPV3
2024-06-27  58.649998   HAPV3
2024-06-28  57.450001   HAPV3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  8.446831   HBOR3
2010-01-05  8.554176   HBOR3
2010-01-06  8.554176   HBOR3
2010-01-07  8.500504   HBOR3
2010-01-08  8.648105   HBOR3
...              ...     ...
2024-06-24  2.015914   HBOR3
2024-06-25  1.968369   HBOR3
2024-06-26  1.939842   HBOR3
2024-06-27  2.015914   HBOR3
2024-06-28  1.958860   HBOR3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   HBRE3
2010-01-05    NaN   HBRE3
2010-01-06    NaN   HBRE3
2010-01-07    NaN   HBRE3
2010-01-08    NaN   HBRE3
...           ...     ...
2024-06-24   5.24   HBRE3
2024-06-25   5.21   HBRE3
2024-06-26   5.10   HBRE3
2024-06-27   5.24   HBRE3
2024-06-28   5.09   HBRE3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   HBSA3
2010-01-05    NaN   HBSA3
2010-01-06    NaN   HBSA3
2010-01-07    NaN   HBSA3
2010-01-08    NaN   HBSA3
...           ...     ...
2024-06-24   3.50   HBSA3
2024-06-25   3.58   HBSA3
2024-06-26   3.61   HBSA3
2024-06-27   3.66   HBSA3
2024-06-28   3.71   HBSA3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   2.291811   HBTS5
2010-01-05   2.291811   HBTS5
2010-01-06   2.291811   HBTS5
2010-01-07   2.291811   HBTS5
2010-01-08   2.291811   HBTS5
...               ...     ...
2024-06-24  36.200001   HBTS5
2024-06-25  36.200001   HBTS5
2024-06-26  36.200001   HBTS5
2024-06-27  36.200001   HBTS5
2024-06-28  35.770000   HBTS5

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  12.000120   HETA4
2010-01-05  12.000120   HETA4
2010-01-06  11.700117   HETA4
2010-01-07  12.000120   HETA4
2010-01-08  12.000120   HETA4
...               ...     ...
2024-06-24   5.350000   HETA4
2024-06-25   5.470000   HETA4
2024-06-26   5.470000   HETA4
2024-06-27   5.460000   HETA4
2024-06-28   5.460000   HETA4

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04   7.20   HOOT4
2010-01-05   7.00   HOOT4
2010-01-06   7.30   HOOT4
2010-01-07   7.00   HOOT4
2010-01-08   7.30   HOOT4
...           ...     ...
2024-06-24   2.61   HOOT4
2024-06-25   2.55   HOOT4
2024-06-26   2.51   HOOT4
2024-06-27   2.51   HOOT4
2024-06-28   2.51   HOOT4

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  14.385295   HYPE3
2010-01-05  14.574946   HYPE3
2010-01-06  15.143896   HYPE3
2010-01-07  15.326521   HYPE3
2010-01-08  15.733919   HYPE3
...               ...     ...
2024-06-24  27.739897   HYPE3
2024-06-25  27.882200   HYPE3
2024-06-26  27.578619   HYPE3
2024-06-27  27.815792   HYPE3
2024-06-28  27.227602   HYPE3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   IFCM3
2010-01-05    NaN   IFCM3
2010-01-06    NaN   IFCM3
2010-01-07    NaN   IFCM3
2010-01-08    NaN   IFCM3
...           ...     ...
2024-06-24   0.34   IFCM3
2024-06-25   0.33   IFCM3
2024-06-26   0.33   IFCM3
2024-06-27   0.36   IFCM3
2024-06-28   0.34   IFCM3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  1.449901   IGTI3
2010-01-05  1.449901   IGTI3
2010-01-06  1.449901   IGTI3
2010-01-07  1.449901   IGTI3
2010-01-08  1.449901   IGTI3
...              ...     ...
2024-06-24  2.614726   IGTI3
2024-06-25  2.547682   IGTI3
2024-06-26  2.528526   IGTI3
2024-06-27  2.538104   IGTI3
2024-06-28  2.509371   IGTI3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  29.949884   INEP3
2010-01-05  30.867702   INEP3
2010-01-06  32.799953   INEP3
2010-01-07  33.814384   INEP3
2010-01-08  35.022041   INEP3
...               ...     ...
2024-06-24   1.900000   INEP3
2024-06-25   1.950000   INEP3
2024-06-26   2.080000   INEP3
2024-06-27   2.100000   INEP3
2024-06-28   2.010000   INEP3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04        NaN   INTB3
2010-01-05        NaN   INTB3
2010-01-06        NaN   INTB3
2010-01-07        NaN   INTB3
2010-01-08        NaN   INTB3
...               ...     ...
2024-06-24  22.479773   INTB3
2024-06-25  22.770836   INTB3
2024-06-26  22.770836   INTB3
2024-06-27  22.935772   INTB3
2024-06-28  22.402157   INTB3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  3.894835   ITSA4
2010-01-05  3.882241   ITSA4
2010-01-06  3.835012   ITSA4
2010-01-07  3.812972   ITSA4
2010-01-08  3.784634   ITSA4
...              ...     ...
2024-06-24  8.699865   ITSA4
2024-06-25  8.717477   ITSA4
2024-06-26  8.673450   ITSA4
2024-06-27  8.664643   ITSA4
2024-06-28  8.647032   ITSA4

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  11.938194   ITUB4
2010-01-05  12.015562   ITUB4
2010-01-06  11.911411   ITUB4
2010-01-07  11.789414   ITUB4
2010-01-08  11.610873   ITUB4
...               ...     ...
2024-06-24  27.486671   ITUB4
2024-06-25  27.571669   ITUB4
2024-06-26  27.520670   ITUB4
2024-06-27  27.571669   ITUB4
2024-06-28  27.546171   ITUB4

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04       NaN   JALL3
2010-01-05       NaN   JALL3
2010-01-06       NaN   JALL3
2010-01-07       NaN   JALL3
2010-01-08       NaN   JALL3
...              ...     ...
2024-06-24  6.645017   JALL3
2024-06-25  6.645017   JALL3
2024-06-26  6.645017   JALL3
2024-06-27  6.823273   JALL3
2024-06-28  6.724242   JALL3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   6.435993   JBSS3
2010-01-05   6.376091   JBSS3
2010-01-06   6.475926   JBSS3
2010-01-07   6.622350   JBSS3
2010-01-08   6.629007   JBSS3
...               ...     ...
2024-06-24  28.551271   JBSS3
2024-06-25  29.048616   JBSS3
2024-06-26  29.370970   JBSS3
2024-06-27  30.080145   JBSS3
2024-06-28  29.720953   JBSS3

[3597 rows x 2 columns]

                  Close Empresa
Date
2010-01-04  5507.179199   JFEN3
2010-01-05  5500.463379   JFEN3
2010-01-06  5507.179199   JFEN3
2010-01-07  5507.179199   JFEN3
2010-01-08  5520.611328   JFEN3
...                 ...     ...
2024-06-24    16.200001   JFEN3
2024-06-25    12.000000   JFEN3
2024-06-26    10.600000   JFEN3
2024-06-27    10.600000   JFEN3
2024-06-28    10.400000   JFEN3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  2.248428   JHSF3
2010-01-05  2.182474   JHSF3
2010-01-06  2.236436   JHSF3
2010-01-07  2.260419   JHSF3
2010-01-08  2.266415   JHSF3
...              ...     ...
2024-06-24  3.739357   JHSF3
2024-06-25  3.758195   JHSF3
2024-06-26  3.682843   JHSF3
2024-06-27  3.748776   JHSF3
2024-06-28  3.720519   JHSF3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  11.782130   JOPA3
2010-01-05  11.782130   JOPA3
2010-01-06  11.782130   JOPA3
2010-01-07  11.782130   JOPA3
2010-01-08  11.782130   JOPA3
...               ...     ...
2024-06-24  20.421629   JOPA3
2024-06-25  20.421629   JOPA3
2024-06-26  20.421629   JOPA3
2024-06-27  20.421629   JOPA3
2024-06-28  20.421629   JOPA3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   JSLG3
2010-01-05    NaN   JSLG3
2010-01-06    NaN   JSLG3
2010-01-07    NaN   JSLG3
2010-01-08    NaN   JSLG3
...           ...     ...
2024-06-24   9.43   JSLG3
2024-06-25   9.40   JSLG3
2024-06-26   9.30   JSLG3
2024-06-27   9.50   JSLG3
2024-06-28   9.40   JSLG3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  1.564717   KEPL3
2010-01-05  1.521252   KEPL3
2010-01-06  1.564717   KEPL3
2010-01-07  1.564717   KEPL3
2010-01-08  1.608181   KEPL3
...              ...     ...
2024-06-24  8.557251   KEPL3
2024-06-25  8.538809   KEPL3
2024-06-26  8.732454   KEPL3
2024-06-27  8.870771   KEPL3
2024-06-28  8.833887   KEPL3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  0.529741   KLBN4
2010-01-05  0.539718   KLBN4
2010-01-06  0.532734   KLBN4
2010-01-07  0.537722   KLBN4
2010-01-08  0.525750   KLBN4
...              ...     ...
2024-06-24  3.933370   KLBN4
2024-06-25  3.952604   KLBN4
2024-06-26  4.000689   KLBN4
2024-06-27  4.077625   KLBN4
2024-06-28  4.096859   KLBN4

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   KRSA3
2010-01-05    NaN   KRSA3
2010-01-06    NaN   KRSA3
2010-01-07    NaN   KRSA3
2010-01-08    NaN   KRSA3
...           ...     ...
2024-06-24    NaN   KRSA3
2024-06-25    NaN   KRSA3
2024-06-26    NaN   KRSA3
2024-06-27    NaN   KRSA3
2024-06-28    NaN   KRSA3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04        NaN   LAND3
2010-01-05        NaN   LAND3
2010-01-06        NaN   LAND3
2010-01-07        NaN   LAND3
2010-01-08        NaN   LAND3
...               ...     ...
2024-06-24  15.039861   LAND3
2024-06-25  15.288535   LAND3
2024-06-26  14.721557   LAND3
2024-06-27  14.821026   LAND3
2024-06-28  14.323676   LAND3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04       NaN   LAVV3
2010-01-05       NaN   LAVV3
2010-01-06       NaN   LAVV3
2010-01-07       NaN   LAVV3
2010-01-08       NaN   LAVV3
...              ...     ...
2024-06-24  7.817298   LAVV3
2024-06-25  7.780250   LAVV3
2024-06-26  7.789512   LAVV3
2024-06-27  7.919182   LAVV3
2024-06-28  7.956232   LAVV3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   6.346869   LEVE3
2010-01-05   6.346869   LEVE3
2010-01-06   6.346869   LEVE3
2010-01-07   6.346869   LEVE3
2010-01-08   6.346869   LEVE3
...               ...     ...
2024-06-24  31.890570   LEVE3
2024-06-25  31.978342   LEVE3
2024-06-26  31.480967   LEVE3
2024-06-27  31.344431   LEVE3
2024-06-28  31.539482   LEVE3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  22.195745   LIGT3
2010-01-05  21.650164   LIGT3
2010-01-06  21.632841   LIGT3
2010-01-07  21.199839   LIGT3
2010-01-08  20.784155   LIGT3
...               ...     ...
2024-06-24   5.060000   LIGT3
2024-06-25   5.110000   LIGT3
2024-06-26   5.080000   LIGT3
2024-06-27   5.050000   LIGT3
2024-06-28   4.980000   LIGT3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  43.928265   LIPR3
2010-01-05  43.928265   LIPR3
2010-01-06  43.928265   LIPR3
2010-01-07  43.928265   LIPR3
2010-01-08  43.928265   LIPR3
...               ...     ...
2024-06-24  48.799999   LIPR3
2024-06-25  48.799999   LIPR3
2024-06-26  48.799999   LIPR3
2024-06-27  48.619999   LIPR3
2024-06-28  48.619999   LIPR3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04       NaN   LJQQ3
2010-01-05       NaN   LJQQ3
2010-01-06       NaN   LJQQ3
2010-01-07       NaN   LJQQ3
2010-01-08       NaN   LJQQ3
...              ...     ...
2024-06-24  3.679000   LJQQ3
2024-06-25  3.622254   LJQQ3
2024-06-26  3.584424   LJQQ3
2024-06-27  3.679000   LJQQ3
2024-06-28  3.518221   LJQQ3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04        NaN   LOGG3
2010-01-05        NaN   LOGG3
2010-01-06        NaN   LOGG3
2010-01-07        NaN   LOGG3
2010-01-08        NaN   LOGG3
...               ...     ...
2024-06-24  21.360037   LOGG3
2024-06-25  21.414711   LOGG3
2024-06-26  21.332697   LOGG3
2024-06-27  21.296247   LOGG3
2024-06-28  21.278023   LOGG3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  36.193428   LOGN3
2010-01-05  36.629494   LOGN3
2010-01-06  36.891132   LOGN3
2010-01-07  36.542278   LOGN3
2010-01-08  37.283592   LOGN3
...               ...     ...
2024-06-24  36.299999   LOGN3
2024-06-25  36.439999   LOGN3
2024-06-26  35.500000   LOGN3
2024-06-27  35.759998   LOGN3
2024-06-28  35.750000   LOGN3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  10.441472   LPSB3
2010-01-05  10.108234   LPSB3
2010-01-06  10.308177   LPSB3
2010-01-07   9.966052   LPSB3
2010-01-08  10.219314   LPSB3
...               ...     ...
2024-06-24   1.698418   LPSB3
2024-06-25   1.698418   LPSB3
2024-06-26   1.679008   LPSB3
2024-06-27   1.737239   LPSB3
2024-06-28   1.795471   LPSB3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   4.384453   LREN3
2010-01-05   4.226503   LREN3
2010-01-06   4.144804   LREN3
2010-01-07   4.106680   LREN3
2010-01-08   4.128465   LREN3
...               ...     ...
2024-06-24  10.906985   LREN3
2024-06-25  10.829993   LREN3
2024-06-26  10.497334   LREN3
2024-06-27  10.904410   LREN3
2024-06-28  10.809137   LREN3

[3597 rows x 2 columns]

                  Close Empresa
Date
2010-01-04  4869.423828   LUPA3
2010-01-05  4903.239258   LUPA3
2010-01-06  5182.216797   LUPA3
2010-01-07  5202.505859   LUPA3
2010-01-08  5266.755371   LUPA3
...                 ...     ...
2024-06-24     1.570000   LUPA3
2024-06-25     1.570000   LUPA3
2024-06-26     1.520000   LUPA3
2024-06-27     1.560000   LUPA3
2024-06-28     1.560000   LUPA3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  0.720509   LUXM3
2010-01-05  0.720509   LUXM3
2010-01-06  0.720509   LUXM3
2010-01-07  0.720509   LUXM3
2010-01-08  0.720509   LUXM3
...              ...     ...
2024-06-24  1.455420   LUXM3
2024-06-25  1.455420   LUXM3
2024-06-26  1.455420   LUXM3
2024-06-27  1.455420   LUXM3
2024-06-28  1.455420   LUXM3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04       NaN   LVTC3
2010-01-05       NaN   LVTC3
2010-01-06       NaN   LVTC3
2010-01-07       NaN   LVTC3
2010-01-08       NaN   LVTC3
...              ...     ...
2024-06-24  3.181726   LVTC3
2024-06-25  3.275306   LVTC3
2024-06-26  3.265948   LVTC3
2024-06-27  3.265948   LVTC3
2024-06-28  3.340812   LVTC3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04       NaN   LWSA3
2010-01-05       NaN   LWSA3
2010-01-06       NaN   LWSA3
2010-01-07       NaN   LWSA3
2010-01-08       NaN   LWSA3
...              ...     ...
2024-06-24  4.039888   LWSA3
2024-06-25  3.931765   LWSA3
2024-06-26  3.872788   LWSA3
2024-06-27  4.079206   LWSA3
2024-06-28  3.980912   LWSA3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  53.900002   MAPT3
2010-01-05  53.900002   MAPT3
2010-01-06  53.900002   MAPT3
2010-01-07  53.900002   MAPT3
2010-01-08  53.900002   MAPT3
...               ...     ...
2024-06-24   4.210000   MAPT3
2024-06-25   4.210000   MAPT3
2024-06-26   4.210000   MAPT3
2024-06-27   4.210000   MAPT3
2024-06-28   4.210000   MAPT3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04       NaN   MATD3
2010-01-05       NaN   MATD3
2010-01-06       NaN   MATD3
2010-01-07       NaN   MATD3
2010-01-08       NaN   MATD3
...              ...     ...
2024-06-24  4.691691   MATD3
2024-06-25  4.573661   MATD3
2024-06-26  4.465467   MATD3
2024-06-27  4.504810   MATD3
2024-06-28  4.475303   MATD3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   MBLY3
2010-01-05    NaN   MBLY3
2010-01-06    NaN   MBLY3
2010-01-07    NaN   MBLY3
2010-01-08    NaN   MBLY3
...           ...     ...
2024-06-24   2.15   MBLY3
2024-06-25   2.14   MBLY3
2024-06-26   2.14   MBLY3
2024-06-27   2.14   MBLY3
2024-06-28   2.17   MBLY3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  10.253165   MDIA3
2010-01-05  10.288509   MDIA3
2010-01-06  10.402126   MDIA3
2010-01-07  10.359206   MDIA3
2010-01-08  10.283461   MDIA3
...               ...     ...
2024-06-24  30.571720   MDIA3
2024-06-25  30.308008   MDIA3
2024-06-26  29.350805   MDIA3
2024-06-27  29.634060   MDIA3
2024-06-28  28.647562   MDIA3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04        NaN   MDNE3
2010-01-05        NaN   MDNE3
2010-01-06        NaN   MDNE3
2010-01-07        NaN   MDNE3
2010-01-08        NaN   MDNE3
...               ...     ...
2024-06-24  10.406336   MDNE3
2024-06-25  10.636312   MDNE3
2024-06-26  10.607564   MDNE3
2024-06-27  10.923779   MDNE3
2024-06-28  10.617146   MDNE3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   MEAL3
2010-01-05    NaN   MEAL3
2010-01-06    NaN   MEAL3
2010-01-07    NaN   MEAL3
2010-01-08    NaN   MEAL3
...           ...     ...
2024-06-24   1.24   MEAL3
2024-06-25   1.24   MEAL3
2024-06-26   1.23   MEAL3
2024-06-27   1.27   MEAL3
2024-06-28   1.25   MEAL3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04       NaN   MELK3
2010-01-05       NaN   MELK3
2010-01-06       NaN   MELK3
2010-01-07       NaN   MELK3
2010-01-08       NaN   MELK3
...              ...     ...
2024-06-24  3.085509   MELK3
2024-06-25  3.111956   MELK3
2024-06-26  2.997352   MELK3
2024-06-27  2.997352   MELK3
2024-06-28  3.041430   MELK3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   6.280768   MERC3
2010-01-05   6.280768   MERC3
2010-01-06   6.280768   MERC3
2010-01-07   6.280768   MERC3
2010-01-08   6.280768   MERC3
...               ...     ...
2024-06-24  15.126800   MERC3
2024-06-25  15.126800   MERC3
2024-06-26  15.126800   MERC3
2024-06-27  15.126800   MERC3
2024-06-28  15.126800   MERC3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  41.368668   MGEL4
2010-01-05  41.687111   MGEL4
2010-01-06  39.950146   MGEL4
2010-01-07  40.529137   MGEL4
2010-01-08  41.252869   MGEL4
...               ...     ...
2024-06-24  13.800000   MGEL4
2024-06-25  13.800000   MGEL4
2024-06-26  13.490000   MGEL4
2024-06-27  13.000000   MGEL4
2024-06-28  12.840000   MGEL4

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   MGLU3
2010-01-05    NaN   MGLU3
2010-01-06    NaN   MGLU3
2010-01-07    NaN   MGLU3
2010-01-08    NaN   MGLU3
...           ...     ...
2024-06-24  12.16   MGLU3
2024-06-25  11.80   MGLU3
2024-06-26  11.48   MGLU3
2024-06-27  12.21   MGLU3
2024-06-28  12.05   MGLU3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04        NaN   MILS3
2010-01-05        NaN   MILS3
2010-01-06        NaN   MILS3
2010-01-07        NaN   MILS3
2010-01-08        NaN   MILS3
...               ...     ...
2024-06-24   9.991312   MILS3
2024-06-25  10.028945   MILS3
2024-06-26   9.812561   MILS3
2024-06-27  10.066578   MILS3
2024-06-28   9.956377   MILS3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   MLAS3
2010-01-05    NaN   MLAS3
2010-01-06    NaN   MLAS3
2010-01-07    NaN   MLAS3
2010-01-08    NaN   MLAS3
...           ...     ...
2024-06-24   2.06   MLAS3
2024-06-25   1.95   MLAS3
2024-06-26   1.89   MLAS3
2024-06-27   2.05   MLAS3
2024-06-28   1.97   MLAS3

[3597 rows x 2 columns]

                 Close Empresa
Date
2010-01-04    0.000001   MMAQ4
2010-01-05    0.000001   MMAQ4
2010-01-06    0.000001   MMAQ4
2010-01-07    0.000001   MMAQ4
2010-01-08    0.000001   MMAQ4
...                ...     ...
2024-06-24  124.072784   MMAQ4
2024-06-25  124.072784   MMAQ4
2024-06-26  124.072784   MMAQ4
2024-06-27  124.072784   MMAQ4
2024-06-28  124.072784   MMAQ4

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   5.587513   MNDL3
2010-01-05   5.587513   MNDL3
2010-01-06   6.228703   MNDL3
2010-01-07   5.770710   MNDL3
2010-01-08   6.228703   MNDL3
...               ...     ...
2024-06-24  12.980000   MNDL3
2024-06-25  12.980000   MNDL3
2024-06-26  13.000000   MNDL3
2024-06-27  12.980000   MNDL3
2024-06-28  12.980000   MNDL3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  47.205257   MNPR3
2010-01-05  47.205257   MNPR3
2010-01-06  50.095371   MNPR3
2010-01-07  48.810879   MNPR3
2010-01-08  49.132000   MNPR3
...               ...     ...
2024-06-24  11.000000   MNPR3
2024-06-25  10.770000   MNPR3
2024-06-26  11.200000   MNPR3
2024-06-27  11.400000   MNPR3
2024-06-28  11.800000   MNPR3

[3597 rows x 2 columns]

                 Close Empresa
Date
2010-01-04   27.401072   MOAR3
2010-01-05   27.401072   MOAR3
2010-01-06   27.401072   MOAR3
2010-01-07   27.401072   MOAR3
2010-01-08   27.401072   MOAR3
...                ...     ...
2024-06-24  344.330414   MOAR3
2024-06-25  344.330414   MOAR3
2024-06-26  344.330414   MOAR3
2024-06-27  344.330414   MOAR3
2024-06-28  344.330414   MOAR3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   MOVI3
2010-01-05    NaN   MOVI3
2010-01-06    NaN   MOVI3
2010-01-07    NaN   MOVI3
2010-01-08    NaN   MOVI3
...           ...     ...
2024-06-24   6.12   MOVI3
2024-06-25   6.06   MOVI3
2024-06-26   6.24   MOVI3
2024-06-27   6.31   MOVI3
2024-06-28   6.04   MOVI3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  13.718737   MRFG3
2010-01-05  14.708747   MRFG3
2010-01-06  15.097679   MRFG3
2010-01-07  15.840189   MRFG3
2010-01-08  16.158407   MRFG3
...               ...     ...
2024-06-24  11.240000   MRFG3
2024-06-25  11.250000   MRFG3
2024-06-26  11.440000   MRFG3
2024-06-27  12.170000   MRFG3
2024-06-28  12.360000   MRFG3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  7.995224   MRVE3
2010-01-05  7.890559   MRVE3
2010-01-06  8.024299   MRVE3
2010-01-07  7.733562   MRVE3
2010-01-08  7.506787   MRVE3
...              ...     ...
2024-06-24  6.990000   MRVE3
2024-06-25  6.980000   MRVE3
2024-06-26  6.740000   MRVE3
2024-06-27  6.960000   MRVE3
2024-06-28  6.680000   MRVE3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  33.252846   MSPA3
2010-01-05  33.252846   MSPA3
2010-01-06  33.252846   MSPA3
2010-01-07  33.252846   MSPA3
2010-01-08  33.252846   MSPA3
...               ...     ...
2024-06-24  42.888870   MSPA3
2024-06-25  42.888870   MSPA3
2024-06-26  42.888870   MSPA3
2024-06-27  42.888870   MSPA3
2024-06-28  42.888870   MSPA3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   MTIG3
2010-01-05    NaN   MTIG3
2010-01-06    NaN   MTIG3
2010-01-07    NaN   MTIG3
2010-01-08    NaN   MTIG3
...           ...     ...
2024-06-24    NaN   MTIG3
2024-06-25    NaN   MTIG3
2024-06-26    NaN   MTIG3
2024-06-27    NaN   MTIG3
2024-06-28    NaN   MTIG3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04       NaN   MTRE3
2010-01-05       NaN   MTRE3
2010-01-06       NaN   MTRE3
2010-01-07       NaN   MTRE3
2010-01-08       NaN   MTRE3
...              ...     ...
2024-06-24  3.065271   MTRE3
2024-06-25  3.047755   MTRE3
2024-06-26  3.021482   MTRE3
2024-06-27  3.091544   MTRE3
2024-06-28  3.056513   MTRE3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  15.275172   MTSA4
2010-01-05  15.275172   MTSA4
2010-01-06  15.275172   MTSA4
2010-01-07  15.275172   MTSA4
2010-01-08  15.275172   MTSA4
...               ...     ...
2024-06-24  38.014717   MTSA4
2024-06-25  39.507313   MTSA4
2024-06-26  40.067039   MTSA4
2024-06-27  40.850658   MTSA4
2024-06-28  41.513000   MTSA4

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   7.769921   MULT3
2010-01-05   7.735340   MULT3
2010-01-06   7.839089   MULT3
2010-01-07   7.804507   MULT3
2010-01-08   7.458663   MULT3
...               ...     ...
2024-06-24  21.718161   MULT3
2024-06-25  21.510872   MULT3
2024-06-26  21.671049   MULT3
2024-06-27  21.922041   MULT3
2024-06-28  21.455616   MULT3

[3597 rows x 2 columns]

             Close Empresa
Date
2010-01-04  30.750   MWET4
2010-01-05  30.250   MWET4
2010-01-06  30.025   MWET4
2010-01-07  30.250   MWET4
2010-01-08  32.000   MWET4
...            ...     ...
2024-06-24   8.160   MWET4
2024-06-25   8.570   MWET4
2024-06-26   8.470   MWET4
2024-06-27   8.170   MWET4
2024-06-28   8.230   MWET4

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   8.184780   MYPK3
2010-01-05   8.330993   MYPK3
2010-01-06   8.788704   MYPK3
2010-01-07   9.017563   MYPK3
2010-01-08   9.106562   MYPK3
...               ...     ...
2024-06-24  11.301021   MYPK3
2024-06-25  11.423244   MYPK3
2024-06-26  11.009563   MYPK3
2024-06-27  11.282217   MYPK3
2024-06-28  11.056572   MYPK3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04        NaN   NEOE3
2010-01-05        NaN   NEOE3
2010-01-06        NaN   NEOE3
2010-01-07        NaN   NEOE3
2010-01-08        NaN   NEOE3
...               ...     ...
2024-06-24  17.565245   NEOE3
2024-06-25  17.517540   NEOE3
2024-06-26  17.660652   NEOE3
2024-06-27  17.756067   NEOE3
2024-06-28  17.717901   NEOE3

[3597 rows x 2 columns]

                  Close Empresa
Date
2010-01-04  1689.675049   NEXP3
2010-01-05  1660.450928   NEXP3
2010-01-06  1705.615601   NEXP3
2010-01-07  1713.585571   NEXP3
2010-01-08  1702.958374   NEXP3
...                 ...     ...
2024-06-24     4.120000   NEXP3
2024-06-25     4.240000   NEXP3
2024-06-26     4.200000   NEXP3
2024-06-27     4.140000   NEXP3
2024-06-28     4.200000   NEXP3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   NGRD3
2010-01-05    NaN   NGRD3
2010-01-06    NaN   NGRD3
2010-01-07    NaN   NGRD3
2010-01-08    NaN   NGRD3
...           ...     ...
2024-06-24  20.00   NGRD3
2024-06-25  20.00   NGRD3
2024-06-26  20.00   NGRD3
2024-06-27  20.75   NGRD3
2024-06-28  20.25   NGRD3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   NINJ3
2010-01-05    NaN   NINJ3
2010-01-06    NaN   NINJ3
2010-01-07    NaN   NINJ3
2010-01-08    NaN   NINJ3
...           ...     ...
2024-06-24    NaN   NINJ3
2024-06-25    NaN   NINJ3
2024-06-26    NaN   NINJ3
2024-06-27    NaN   NINJ3
2024-06-28    NaN   NINJ3

[3597 rows x 2 columns]

              Close Empresa
Date
2010-01-04  6000.00   NORD3
2010-01-05  6000.00   NORD3
2010-01-06  6000.00   NORD3
2010-01-07  6000.00   NORD3
2010-01-08  6000.00   NORD3
...             ...     ...
2024-06-24     6.85   NORD3
2024-06-25     6.30   NORD3
2024-06-26     6.55   NORD3
2024-06-27     6.47   NORD3
2024-06-28     6.01   NORD3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   NTCO3
2010-01-05    NaN   NTCO3
2010-01-06    NaN   NTCO3
2010-01-07    NaN   NTCO3
2010-01-08    NaN   NTCO3
...           ...     ...
2024-06-24  15.41   NTCO3
2024-06-25  15.08   NTCO3
2024-06-26  15.38   NTCO3
2024-06-27  15.86   NTCO3
2024-06-28  15.54   NTCO3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   NUTR3
2010-01-05    NaN   NUTR3
2010-01-06    NaN   NUTR3
2010-01-07    NaN   NUTR3
2010-01-08    NaN   NUTR3
...           ...     ...
2024-06-24   5.53   NUTR3
2024-06-25   5.24   NUTR3
2024-06-26   5.15   NUTR3
2024-06-27   5.07   NUTR3
2024-06-28   5.06   NUTR3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04        NaN   ODER4
2010-01-05        NaN   ODER4
2010-01-06        NaN   ODER4
2010-01-07        NaN   ODER4
2010-01-08        NaN   ODER4
...               ...     ...
2024-06-24  99.139465   ODER4
2024-06-25  99.139465   ODER4
2024-06-26  99.139465   ODER4
2024-06-27  99.139465   ODER4
2024-06-28  99.139465   ODER4

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   2.958572   ODPV3
2010-01-05   2.901456   ODPV3
2010-01-06   2.969994   ODPV3
2010-01-07   3.013402   ODPV3
2010-01-08   3.029395   ODPV3
...               ...     ...
2024-06-24  10.797269   ODPV3
2024-06-25  10.787452   ODPV3
2024-06-26  10.581083   ODPV3
2024-06-27  10.656127   ODPV3
2024-06-28  10.656127   ODPV3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04        NaN   OFSA3
2010-01-05        NaN   OFSA3
2010-01-06        NaN   OFSA3
2010-01-07        NaN   OFSA3
2010-01-08        NaN   OFSA3
...               ...     ...
2024-06-24  17.984480   OFSA3
2024-06-25  18.332378   OFSA3
2024-06-26  18.448345   OFSA3
2024-06-27  18.854229   OFSA3
2024-06-28  18.477339   OFSA3

[3597 rows x 2 columns]

                   Close Empresa
Date
2010-01-04  18903.619141   OIBR3
2010-01-05  19174.154297   OIBR3
2010-01-06  19309.421875   OIBR3
2010-01-07  19241.787109   OIBR3
2010-01-08  19174.154297   OIBR3
...                  ...     ...
2024-06-24      4.600000   OIBR3
2024-06-25      4.800000   OIBR3
2024-06-26      4.820000   OIBR3
2024-06-27      5.220000   OIBR3
2024-06-28      5.400000   OIBR3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   ONCO3
2010-01-05    NaN   ONCO3
2010-01-06    NaN   ONCO3
2010-01-07    NaN   ONCO3
2010-01-08    NaN   ONCO3
...           ...     ...
2024-06-24   5.89   ONCO3
2024-06-25   5.75   ONCO3
2024-06-26   5.73   ONCO3
2024-06-27   6.25   ONCO3
2024-06-28   6.18   ONCO3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   OPCT3
2010-01-05    NaN   OPCT3
2010-01-06    NaN   OPCT3
2010-01-07    NaN   OPCT3
2010-01-08    NaN   OPCT3
...           ...     ...
2024-06-24   6.48   OPCT3
2024-06-25   6.53   OPCT3
2024-06-26   6.60   OPCT3
2024-06-27   6.52   OPCT3
2024-06-28   6.46   OPCT3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04        NaN   ORVR3
2010-01-05        NaN   ORVR3
2010-01-06        NaN   ORVR3
2010-01-07        NaN   ORVR3
2010-01-08        NaN   ORVR3
...               ...     ...
2024-06-24  38.110001   ORVR3
2024-06-25  37.880001   ORVR3
2024-06-26  37.740002   ORVR3
2024-06-27  38.950001   ORVR3
2024-06-28  38.599998   ORVR3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04   0.22   OSXB3
2010-01-05   0.22   OSXB3
2010-01-06   0.22   OSXB3
2010-01-07   0.22   OSXB3
2010-01-08   0.22   OSXB3
...           ...     ...
2024-06-24   3.89   OSXB3
2024-06-25   3.80   OSXB3
2024-06-26   3.80   OSXB3
2024-06-27   3.79   OSXB3
2024-06-28   3.92   OSXB3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   1.500249   PATI4
2010-01-05   1.500249   PATI4
2010-01-06   1.500249   PATI4
2010-01-07   1.500249   PATI4
2010-01-08   1.500249   PATI4
...               ...     ...
2024-06-24  27.436665   PATI4
2024-06-25  27.436665   PATI4
2024-06-26  27.436665   PATI4
2024-06-27  27.436665   PATI4
2024-06-28  27.436665   PATI4

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  2.014741   PCAR3
2010-01-05  2.014741   PCAR3
2010-01-06  2.014741   PCAR3
2010-01-07  2.014741   PCAR3
2010-01-08  2.014741   PCAR3
...              ...     ...
2024-06-24  2.940000   PCAR3
2024-06-25  2.830000   PCAR3
2024-06-26  2.610000   PCAR3
2024-06-27  2.820000   PCAR3
2024-06-28  2.700000   PCAR3

[3597 rows x 2 columns]

                  Close Empresa
Date
2010-01-04  46262340.00   PDGR3
2010-01-05  45557124.00   PDGR3
2010-01-06  45105784.00   PDGR3
2010-01-07  44710860.00   PDGR3
2010-01-08  43159380.00   PDGR3
...                 ...     ...
2024-06-24        22.50   PDGR3
2024-06-25        22.50   PDGR3
2024-06-26        21.25   PDGR3
2024-06-27        22.50   PDGR3
2024-06-28        21.25   PDGR3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  48.821953   PDTC3
2010-01-05  48.280487   PDTC3
2010-01-06  48.460979   PDTC3
2010-01-07  47.558537   PDTC3
2010-01-08  48.190243   PDTC3
...               ...     ...
2024-06-24   1.850000   PDTC3
2024-06-25   2.000000   PDTC3
2024-06-26   1.960000   PDTC3
2024-06-27   2.010000   PDTC3
2024-06-28   1.980000   PDTC3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  11.501789   PEAB3
2010-01-05  11.501789   PEAB3
2010-01-06  11.501789   PEAB3
2010-01-07  11.501789   PEAB3
2010-01-08  11.501789   PEAB3
...               ...     ...
2024-06-24  43.178841   PEAB3
2024-06-25  43.178841   PEAB3
2024-06-26  42.186226   PEAB3
2024-06-27  42.186226   PEAB3
2024-06-28  44.171455   PEAB3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  13.449583   PETR4
2010-01-05  13.334258   PETR4
2010-01-06  13.514446   PETR4
2010-01-07  13.388316   PETR4
2010-01-08  13.316239   PETR4
...               ...     ...
2024-06-24  33.643085   PETR4
2024-06-25  33.615852   PETR4
2024-06-26  33.670319   PETR4
2024-06-27  34.233154   PETR4
2024-06-28  34.541805   PETR4

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04       NaN   PETZ3
2010-01-05       NaN   PETZ3
2010-01-06       NaN   PETZ3
2010-01-07       NaN   PETZ3
2010-01-08       NaN   PETZ3
...              ...     ...
2024-06-24  3.263308   PETZ3
2024-06-25  3.225690   PETZ3
2024-06-26  3.094029   PETZ3
2024-06-27  3.394969   PETZ3
2024-06-28  3.413777   PETZ3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  11.293366   PFRM3
2010-01-05  11.454220   PFRM3
2010-01-06  11.527946   PFRM3
2010-01-07  11.400601   PFRM3
2010-01-08  11.802739   PFRM3
...               ...     ...
2024-06-24   4.727387   PFRM3
2024-06-25   4.644773   PFRM3
2024-06-26   4.681490   PFRM3
2024-06-27   4.874258   PFRM3
2024-06-28   4.791643   PFRM3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04       NaN   PGMN3
2010-01-05       NaN   PGMN3
2010-01-06       NaN   PGMN3
2010-01-07       NaN   PGMN3
2010-01-08       NaN   PGMN3
...              ...     ...
2024-06-24  2.175271   PGMN3
2024-06-25  2.248698   PGMN3
2024-06-26  2.239520   PGMN3
2024-06-27  2.358838   PGMN3
2024-06-28  2.340481   PGMN3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  5.959497   PINE4
2010-01-05  6.064341   PINE4
2010-01-06  6.108485   PINE4
2010-01-07  5.987087   PINE4
2010-01-08  6.174700   PINE4
...              ...     ...
2024-06-24  3.806097   PINE4
2024-06-25  3.741898   PINE4
2024-06-26  3.714384   PINE4
2024-06-27  3.778583   PINE4
2024-06-28  3.796926   PINE4

[3597 rows x 2 columns]

                 Close Empresa
Date
2010-01-04  118.320953   PLAS3
2010-01-05  133.668030   PLAS3
2010-01-06  130.697632   PLAS3
2010-01-07  139.113754   PLAS3
2010-01-08  158.421356   PLAS3
...                ...     ...
2024-06-24    5.110000   PLAS3
2024-06-25    5.100000   PLAS3
2024-06-26    5.100000   PLAS3
2024-06-27    5.100000   PLAS3
2024-06-28    5.000000   PLAS3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04       NaN   PLPL3
2010-01-05       NaN   PLPL3
2010-01-06       NaN   PLPL3
2010-01-07       NaN   PLPL3
2010-01-08       NaN   PLPL3
...              ...     ...
2024-06-24  8.862881   PLPL3
2024-06-25  9.332676   PLPL3
2024-06-26  9.531436   PLPL3
2024-06-27  9.712127   PLPL3
2024-06-28  9.305573   PLPL3

[3597 rows x 2 columns]

                 Close Empresa
Date
2010-01-04  106.772034   PMAM3
2010-01-05  107.714134   PMAM3
2010-01-06  108.342209   PMAM3
2010-01-07  108.342209   PMAM3
2010-01-08  112.581688   PMAM3
...                ...     ...
2024-06-24    2.380000   PMAM3
2024-06-25    2.350000   PMAM3
2024-06-26    2.400000   PMAM3
2024-06-27    2.430000   PMAM3
2024-06-28    2.380000   PMAM3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  1.570776   PNVL3
2010-01-05  1.586914   PNVL3
2010-01-06  1.586914   PNVL3
2010-01-07  1.533121   PNVL3
2010-01-08  1.640708   PNVL3
...              ...     ...
2024-06-24  9.386369   PNVL3
2024-06-25  9.262236   PNVL3
2024-06-26  9.166749   PNVL3
2024-06-27  9.553386   PNVL3
2024-06-28  9.303246   PNVL3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  1.060510   POMO4
2010-01-05  1.063532   POMO4
2010-01-06  1.093746   POMO4
2010-01-07  1.117918   POMO4
2010-01-08  1.139067   POMO4
...              ...     ...
2024-06-24  6.041705   POMO4
2024-06-25  5.837530   POMO4
2024-06-26  5.791127   POMO4
2024-06-27  6.097389   POMO4
2024-06-28  5.893215   POMO4

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04        NaN   PORT3
2010-01-05        NaN   PORT3
2010-01-06        NaN   PORT3
2010-01-07        NaN   PORT3
2010-01-08        NaN   PORT3
...               ...     ...
2024-06-24  13.587117   PORT3
2024-06-25  13.697805   PORT3
2024-06-26  13.725478   PORT3
2024-06-27  14.011426   PORT3
2024-06-28  14.020649   PORT3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  14.724008   POSI3
2010-01-05  14.763374   POSI3
2010-01-06  14.546848   POSI3
2010-01-07  14.336879   POSI3
2010-01-08  13.838206   POSI3
...               ...     ...
2024-06-24   8.207650   POSI3
2024-06-25   8.150320   POSI3
2024-06-26   7.825454   POSI3
2024-06-27   7.806345   POSI3
2024-06-28   7.500588   POSI3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04        NaN   PRIO3
2010-01-05        NaN   PRIO3
2010-01-06        NaN   PRIO3
2010-01-07        NaN   PRIO3
2010-01-08        NaN   PRIO3
...               ...     ...
2024-06-24  42.080002   PRIO3
2024-06-25  42.020000   PRIO3
2024-06-26  43.020000   PRIO3
2024-06-27  43.180000   PRIO3
2024-06-28  43.759998   PRIO3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04        NaN   PRNR3
2010-01-05        NaN   PRNR3
2010-01-06        NaN   PRNR3
2010-01-07        NaN   PRNR3
2010-01-08        NaN   PRNR3
...               ...     ...
2024-06-24  10.378609   PRNR3
2024-06-25  10.368639   PRNR3
2024-06-26  10.428458   PRNR3
2024-06-27  10.867131   PRNR3
2024-06-28  10.767433   PRNR3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   5.464381   PSSA3
2010-01-05   5.371764   PSSA3
2010-01-06   5.490845   PSSA3
2010-01-07   5.556998   PSSA3
2010-01-08   5.554351   PSSA3
...               ...     ...
2024-06-24  29.772243   PSSA3
2024-06-25  29.840845   PSSA3
2024-06-26  29.958445   PSSA3
2024-06-27  30.311243   PSSA3
2024-06-28  30.330843   PSSA3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  0.903082   PTBL3
2010-01-05  0.922434   PTBL3
2010-01-06  0.922434   PTBL3
2010-01-07  0.909533   PTBL3
2010-01-08  0.974039   PTBL3
...              ...     ...
2024-06-24  4.300000   PTBL3
2024-06-25  4.270000   PTBL3
2024-06-26  4.500000   PTBL3
2024-06-27  4.730000   PTBL3
2024-06-28  4.680000   PTBL3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  0.820733   PTNT4
2010-01-05  0.820733   PTNT4
2010-01-06  0.820733   PTNT4
2010-01-07  0.820733   PTNT4
2010-01-08  0.820733   PTNT4
...              ...     ...
2024-06-24  6.080000   PTNT4
2024-06-25  5.860000   PTNT4
2024-06-26  5.900000   PTNT4
2024-06-27  5.990000   PTNT4
2024-06-28  5.950000   PTNT4

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   QUAL3
2010-01-05    NaN   QUAL3
2010-01-06    NaN   QUAL3
2010-01-07    NaN   QUAL3
2010-01-08    NaN   QUAL3
...           ...     ...
2024-06-24   1.49   QUAL3
2024-06-25   1.47   QUAL3
2024-06-26   1.41   QUAL3
2024-06-27   1.44   QUAL3
2024-06-28   1.40   QUAL3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   1.545219   RADL3
2010-01-05   1.507677   RADL3
2010-01-06   1.522910   RADL3
2010-01-07   1.512574   RADL3
2010-01-08   1.539233   RADL3
...               ...     ...
2024-06-24  25.835752   RADL3
2024-06-25  26.023252   RADL3
2024-06-26  26.062725   RADL3
2024-06-27  26.191019   RADL3
2024-06-28  25.342325   RADL3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04        NaN   RAIL3
2010-01-05        NaN   RAIL3
2010-01-06        NaN   RAIL3
2010-01-07        NaN   RAIL3
2010-01-08        NaN   RAIL3
...               ...     ...
2024-06-24  19.417112   RAIL3
2024-06-25  19.493784   RAIL3
2024-06-26  19.742968   RAIL3
2024-06-27  20.212582   RAIL3
2024-06-28  19.857973   RAIL3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   RAIZ4
2010-01-05    NaN   RAIZ4
2010-01-06    NaN   RAIZ4
2010-01-07    NaN   RAIZ4
2010-01-08    NaN   RAIZ4
...           ...     ...
2024-06-24   2.88   RAIZ4
2024-06-25   2.87   RAIZ4
2024-06-26   2.87   RAIZ4
2024-06-27   2.98   RAIZ4
2024-06-28   2.95   RAIZ4

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  0.547599   RANI3
2010-01-05  0.547599   RANI3
2010-01-06  0.571937   RANI3
2010-01-07  0.584106   RANI3
2010-01-08  0.584106   RANI3
...              ...     ...
2024-06-24  7.673479   RANI3
2024-06-25  7.609073   RANI3
2024-06-26  7.627474   RANI3
2024-06-27  7.728683   RANI3
2024-06-28  7.793088   RANI3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   5.248909   RAPT4
2010-01-05   5.282235   RAPT4
2010-01-06   5.308897   RAPT4
2010-01-07   5.205584   RAPT4
2010-01-08   5.295567   RAPT4
...               ...     ...
2024-06-24  10.190654   RAPT4
2024-06-25  10.459841   RAPT4
2024-06-26  10.315632   RAPT4
2024-06-27  10.700186   RAPT4
2024-06-28  10.498296   RAPT4

[3597 rows x 2 columns]

                  Close Empresa
Date
2010-01-04  2121.708496   RCSL3
2010-01-05  2305.421631   RCSL3
2010-01-06  2305.421631   RCSL3
2010-01-07  2305.421631   RCSL3
2010-01-08  2305.421631   RCSL3
...                 ...     ...
2024-06-24     2.890000   RCSL3
2024-06-25     2.950000   RCSL3
2024-06-26     3.000000   RCSL3
2024-06-27     2.830000   RCSL3
2024-06-28     2.830000   RCSL3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  13.349173   RDNI3
2010-01-05  13.261875   RDNI3
2010-01-06  13.087282   RDNI3
2010-01-07  13.094555   RDNI3
2010-01-08  12.949060   RDNI3
...               ...     ...
2024-06-24   3.080000   RDNI3
2024-06-25   3.100000   RDNI3
2024-06-26   3.060000   RDNI3
2024-06-27   3.060000   RDNI3
2024-06-28   3.060000   RDNI3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04        NaN   RDOR3
2010-01-05        NaN   RDOR3
2010-01-06        NaN   RDOR3
2010-01-07        NaN   RDOR3
2010-01-08        NaN   RDOR3
...               ...     ...
2024-06-24  26.175383   RDOR3
2024-06-25  25.693386   RDOR3
2024-06-26  25.958973   RDOR3
2024-06-27  26.942644   RDOR3
2024-06-28  26.755747   RDOR3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04        NaN   RECV3
2010-01-05        NaN   RECV3
2010-01-06        NaN   RECV3
2010-01-07        NaN   RECV3
2010-01-08        NaN   RECV3
...               ...     ...
2024-06-24  16.238398   RECV3
2024-06-25  16.151047   RECV3
2024-06-26  16.194723   RECV3
2024-06-27  16.343216   RECV3
2024-06-28  16.194723   RECV3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  2.491265   REDE3
2010-01-05  2.417305   REDE3
2010-01-06  2.432876   REDE3
2010-01-07  2.452339   REDE3
2010-01-08  2.452339   REDE3
...              ...     ...
2024-06-24  6.035124   REDE3
2024-06-25  6.035124   REDE3
2024-06-26  5.998658   REDE3
2024-06-27  6.080707   REDE3
2024-06-28  6.053357   REDE3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   4.128338   RENT3
2010-01-05   4.183383   RENT3
2010-01-06   4.509416   RENT3
2010-01-07   4.318878   RENT3
2010-01-08   4.359102   RENT3
...               ...     ...
2024-06-24  39.725117   RENT3
2024-06-25  39.772205   RENT3
2024-06-26  39.932312   RENT3
2024-06-27  40.825241   RENT3
2024-06-28  40.015404   RENT3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   RNEW4
2010-01-05    NaN   RNEW4
2010-01-06    NaN   RNEW4
2010-01-07    NaN   RNEW4
2010-01-08    NaN   RNEW4
...           ...     ...
2024-06-24   1.80   RNEW4
2024-06-25   1.78   RNEW4
2024-06-26   1.80   RNEW4
2024-06-27   1.86   RNEW4
2024-06-28   1.82   RNEW4

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  3.649821   ROMI3
2010-01-05  3.743489   ROMI3
2010-01-06  3.805932   ROMI3
2010-01-07  3.809053   ROMI3
2010-01-08  3.855886   ROMI3
...              ...     ...
2024-06-24  9.581635   ROMI3
2024-06-25  9.701175   ROMI3
2024-06-26  9.646001   ROMI3
2024-06-27  9.719565   ROMI3
2024-06-28  9.627611   ROMI3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  4.967587   RPAD3
2010-01-05  4.967587   RPAD3
2010-01-06  6.040586   RPAD3
2010-01-07  4.818559   RPAD3
2010-01-08  4.838430   RPAD3
...              ...     ...
2024-06-24  8.690000   RPAD3
2024-06-25  8.690000   RPAD3
2024-06-26  8.690000   RPAD3
2024-06-27  8.690000   RPAD3
2024-06-28  8.690000   RPAD3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  9.182175   RPMG3
2010-01-05  8.982562   RPMG3
2010-01-06  8.583337   RPMG3
2010-01-07  8.184112   RPMG3
2010-01-08  8.184112   RPMG3
...              ...     ...
2024-06-24  2.460000   RPMG3
2024-06-25  2.450000   RPMG3
2024-06-26  2.440000   RPMG3
2024-06-27  2.520000   RPMG3
2024-06-28  2.560000   RPMG3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   RRRP3
2010-01-05    NaN   RRRP3
2010-01-06    NaN   RRRP3
2010-01-07    NaN   RRRP3
2010-01-08    NaN   RRRP3
...           ...     ...
2024-06-24    NaN   RRRP3
2024-06-25    NaN   RRRP3
2024-06-26    NaN   RRRP3
2024-06-27    NaN   RRRP3
2024-06-28    NaN   RRRP3

[3597 rows x 2 columns]

                 Close Empresa
Date
2010-01-04  359.234344   RSID3
2010-01-05  352.141205   RSID3
2010-01-06  356.946259   RSID3
2010-01-07  350.081909   RSID3
2010-01-08  346.649689   RSID3
...                ...     ...
2024-06-24    5.350000   RSID3
2024-06-25    5.320000   RSID3
2024-06-26    5.390000   RSID3
2024-06-27    5.210000   RSID3
2024-06-28    5.340000   RSID3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   8.606015   RSUL4
2010-01-05   8.606015   RSUL4
2010-01-06   8.606015   RSUL4
2010-01-07   8.606015   RSUL4
2010-01-08   8.606015   RSUL4
...               ...     ...
2024-06-24  65.281113   RSUL4
2024-06-25  64.594452   RSUL4
2024-06-26  66.238571   RSUL4
2024-06-27  66.248245   RSUL4
2024-06-28  66.248245   RSUL4

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   4.929852   SANB3
2010-01-05   5.144192   SANB3
2010-01-06   5.144192   SANB3
2010-01-07   4.929852   SANB3
2010-01-08   4.929852   SANB3
...               ...     ...
2024-06-24  12.533088   SANB3
2024-06-25  12.533088   SANB3
2024-06-26  12.306926   SANB3
2024-06-27  12.401159   SANB3
2024-06-28  12.372890   SANB3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  0.269646   SAPR4
2010-01-05  0.269646   SAPR4
2010-01-06  0.269646   SAPR4
2010-01-07  0.269646   SAPR4
2010-01-08  0.269646   SAPR4
...              ...     ...
2024-06-24  5.078849   SAPR4
2024-06-25  5.069764   SAPR4
2024-06-26  5.015250   SAPR4
2024-06-27  5.069764   SAPR4
2024-06-28  5.078849   SAPR4

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04        NaN   SBFG3
2010-01-05        NaN   SBFG3
2010-01-06        NaN   SBFG3
2010-01-07        NaN   SBFG3
2010-01-08        NaN   SBFG3
...               ...     ...
2024-06-24  11.205968   SBFG3
2024-06-25  11.262996   SBFG3
2024-06-26  11.538630   SBFG3
2024-06-27  11.624171   SBFG3
2024-06-28  11.405565   SBFG3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   7.490690   SBSP3
2010-01-05   7.501723   SBSP3
2010-01-06   7.499517   SBSP3
2010-01-07   7.380372   SBSP3
2010-01-08   7.503929   SBSP3
...               ...     ...
2024-06-24  75.400276   SBSP3
2024-06-25  75.090668   SBSP3
2024-06-26  73.774811   SBSP3
2024-06-27  71.704285   SBSP3
2024-06-28  72.536362   SBSP3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  13.563924   SCAR3
2010-01-05  13.245060   SCAR3
2010-01-06  13.089718   SCAR3
2010-01-07  13.089718   SCAR3
2010-01-08  13.882784   SCAR3
...               ...     ...
2024-06-24  22.190001   SCAR3
2024-06-25  22.719999   SCAR3
2024-06-26  22.389999   SCAR3
2024-06-27  23.879999   SCAR3
2024-06-28  24.299999   SCAR3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04       NaN   SEER3
2010-01-05       NaN   SEER3
2010-01-06       NaN   SEER3
2010-01-07       NaN   SEER3
2010-01-08       NaN   SEER3
...              ...     ...
2024-06-24  5.017055   SEER3
2024-06-25  4.948862   SEER3
2024-06-26  4.783250   SEER3
2024-06-27  4.968346   SEER3
2024-06-28  4.685832   SEER3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   SEQL3
2010-01-05    NaN   SEQL3
2010-01-06    NaN   SEQL3
2010-01-07    NaN   SEQL3
2010-01-08    NaN   SEQL3
...           ...     ...
2024-06-24   4.93   SEQL3
2024-06-25   4.60   SEQL3
2024-06-26   4.47   SEQL3
2024-06-27   4.37   SEQL3
2024-06-28   4.41   SEQL3

[3597 rows x 2 columns]

                 Close Empresa
Date
2010-01-04   92.191978   SGPS3
2010-01-05   91.805428   SGPS3
2010-01-06   91.418884   SGPS3
2010-01-07   95.670921   SGPS3
2010-01-08  100.502792   SGPS3
...                ...     ...
2024-06-24    1.800000   SGPS3
2024-06-25    1.850000   SGPS3
2024-06-26    1.850000   SGPS3
2024-06-27    1.850000   SGPS3
2024-06-28    1.850000   SGPS3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   SHOW3
2010-01-05    NaN   SHOW3
2010-01-06    NaN   SHOW3
2010-01-07    NaN   SHOW3
2010-01-08    NaN   SHOW3
...           ...     ...
2024-06-24   14.9   SHOW3
2024-06-25   15.0   SHOW3
2024-06-26   15.1   SHOW3
2024-06-27   15.1   SHOW3
2024-06-28   14.7   SHOW3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  0.543608   SHUL4
2010-01-05  0.547665   SHUL4
2010-01-06  0.557807   SHUL4
2010-01-07  0.564906   SHUL4
2010-01-08  0.565920   SHUL4
...              ...     ...
2024-06-24  5.518520   SHUL4
2024-06-25  5.564431   SHUL4
2024-06-26  5.527702   SHUL4
2024-06-27  5.678026   SHUL4
2024-06-28  5.603192   SHUL4

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04       NaN   SIMH3
2010-01-05       NaN   SIMH3
2010-01-06       NaN   SIMH3
2010-01-07       NaN   SIMH3
2010-01-08       NaN   SIMH3
...              ...     ...
2024-06-24  5.542996   SIMH3
2024-06-25  5.473956   SIMH3
2024-06-26  5.444366   SIMH3
2024-06-27  5.503544   SIMH3
2024-06-28  5.256969   SIMH3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   1.933457   SLCE3
2010-01-05   1.945247   SLCE3
2010-01-06   2.044277   SLCE3
2010-01-07   2.098508   SLCE3
2010-01-08   2.228192   SLCE3
...               ...     ...
2024-06-24  16.956348   SLCE3
2024-06-25  16.907734   SLCE3
2024-06-26  16.898012   SLCE3
2024-06-27  17.063297   SLCE3
2024-06-28  16.966072   SLCE3

[3597 rows x 2 columns]

                 Close Empresa
Date
2010-01-04  818.265991   SLED4
2010-01-05  813.438416   SLED4
2010-01-06  818.265991   SLED4
2010-01-07  818.265991   SLED4
2010-01-08  823.093506   SLED4
...                ...     ...
2024-06-24    1.600000   SLED4
2024-06-25    1.600000   SLED4
2024-06-26    1.600000   SLED4
2024-06-27    1.600000   SLED4
2024-06-28    1.600000   SLED4

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04        NaN   SMFT3
2010-01-05        NaN   SMFT3
2010-01-06        NaN   SMFT3
2010-01-07        NaN   SMFT3
2010-01-08        NaN   SMFT3
...               ...     ...
2024-06-24  21.134089   SMFT3
2024-06-25  21.250528   SMFT3
2024-06-26  21.075867   SMFT3
2024-06-27  21.541634   SMFT3
2024-06-28  20.959425   SMFT3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   4.146883   SMTO3
2010-01-05   4.372407   SMTO3
2010-01-06   4.372407   SMTO3
2010-01-07   4.296466   SMTO3
2010-01-08   4.429940   SMTO3
...               ...     ...
2024-06-24  32.067848   SMTO3
2024-06-25  31.874378   SMTO3
2024-06-26  32.174255   SMTO3
2024-06-27  31.845354   SMTO3
2024-06-28  31.661560   SMTO3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04        NaN   SOJA3
2010-01-05        NaN   SOJA3
2010-01-06        NaN   SOJA3
2010-01-07        NaN   SOJA3
2010-01-08        NaN   SOJA3
...               ...     ...
2024-06-24  14.330565   SOJA3
2024-06-25  13.824322   SOJA3
2024-06-26  13.950883   SOJA3
2024-06-27  14.320830   SOJA3
2024-06-28  14.408448   SOJA3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   SOMA3
2010-01-05    NaN   SOMA3
2010-01-06    NaN   SOMA3
2010-01-07    NaN   SOMA3
2010-01-08    NaN   SOMA3
...           ...     ...
2024-06-24    NaN   SOMA3
2024-06-25    NaN   SOMA3
2024-06-26    NaN   SOMA3
2024-06-27    NaN   SOMA3
2024-06-28    NaN   SOMA3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   2.918839   SOND3
2010-01-05   2.918839   SOND3
2010-01-06   2.918839   SOND3
2010-01-07   2.918839   SOND3
2010-01-08   2.918839   SOND3
...               ...     ...
2024-06-24  40.428329   SOND3
2024-06-25  40.428329   SOND3
2024-06-26  40.428329   SOND3
2024-06-27  40.428329   SOND3
2024-06-28  40.428329   SOND3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   SRNA3
2010-01-05    NaN   SRNA3
2010-01-06    NaN   SRNA3
2010-01-07    NaN   SRNA3
2010-01-08    NaN   SRNA3
...           ...     ...
2024-06-24   8.49   SRNA3
2024-06-25   8.44   SRNA3
2024-06-26   8.57   SRNA3
2024-06-27   9.00   SRNA3
2024-06-28   8.81   SRNA3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   0.297408   STBP3
2010-01-05   0.297408   STBP3
2010-01-06   0.297408   STBP3
2010-01-07   0.297408   STBP3
2010-01-08   0.297408   STBP3
...               ...     ...
2024-06-24  11.019433   STBP3
2024-06-25  11.242465   STBP3
2024-06-26  11.151600   STBP3
2024-06-27  11.267246   STBP3
2024-06-28  11.275506   STBP3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  13.465051   SUZB3
2010-01-05  13.465051   SUZB3
2010-01-06  13.465051   SUZB3
2010-01-07  13.465051   SUZB3
2010-01-08  13.465051   SUZB3
...               ...     ...
2024-06-24  48.062416   SUZB3
2024-06-25  48.130203   SUZB3
2024-06-26  49.205143   SUZB3
2024-06-27  55.199631   SUZB3
2024-06-28  55.209312   SUZB3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  1.974453   SYNE3
2010-01-05  1.974453   SYNE3
2010-01-06  1.974453   SYNE3
2010-01-07  1.974453   SYNE3
2010-01-08  2.015587   SYNE3
...              ...     ...
2024-06-24  6.133626   SYNE3
2024-06-25  6.133626   SYNE3
2024-06-26  6.140441   SYNE3
2024-06-27  6.235852   SYNE3
2024-06-28  6.235852   SYNE3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04        NaN   TAEE4
2010-01-05        NaN   TAEE4
2010-01-06        NaN   TAEE4
2010-01-07        NaN   TAEE4
2010-01-08        NaN   TAEE4
...               ...     ...
2024-06-24  10.484217   TAEE4
2024-06-25  10.548991   TAEE4
2024-06-26  10.502724   TAEE4
2024-06-27  10.576752   TAEE4
2024-06-28  10.604513   TAEE4

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  30.537796   TASA4
2010-01-05  30.440382   TASA4
2010-01-06  30.635202   TASA4
2010-01-07  31.024836   TASA4
2010-01-08  33.070435   TASA4
...               ...     ...
2024-06-24  10.118181   TASA4
2024-06-25  10.209090   TASA4
2024-06-26  10.100000   TASA4
2024-06-27  10.390909   TASA4
2024-06-28  10.427272   TASA4

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  72.545914   TCSA3
2010-01-05  72.545914   TCSA3
2010-01-06  74.917603   TCSA3
2010-01-07  74.917603   TCSA3
2010-01-08  75.684921   TCSA3
...               ...     ...
2024-06-24   2.000000   TCSA3
2024-06-25   1.990000   TCSA3
2024-06-26   1.950000   TCSA3
2024-06-27   1.970000   TCSA3
2024-06-28   1.950000   TCSA3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   TECN3
2010-01-05    NaN   TECN3
2010-01-06    NaN   TECN3
2010-01-07    NaN   TECN3
2010-01-08    NaN   TECN3
...           ...     ...
2024-06-24   4.45   TECN3
2024-06-25   4.84   TECN3
2024-06-26   4.68   TECN3
2024-06-27   4.67   TECN3
2024-06-28   4.53   TECN3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  31.821165   TEKA4
2010-01-05  31.821165   TEKA4
2010-01-06  32.815575   TEKA4
2010-01-07  32.815575   TEKA4
2010-01-08  31.821165   TEKA4
...               ...     ...
2024-06-24  30.900000   TEKA4
2024-06-25  30.900000   TEKA4
2024-06-26  30.900000   TEKA4
2024-06-27  30.900000   TEKA4
2024-06-28  30.900000   TEKA4

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  71.087555   TELB4
2010-01-05  80.565895   TELB4
2010-01-06  77.722389   TELB4
2010-01-07  79.618057   TELB4
2010-01-08  83.409393   TELB4
...               ...     ...
2024-06-24   8.900000   TELB4
2024-06-25   8.930000   TELB4
2024-06-26   8.860000   TELB4
2024-06-27   8.870000   TELB4
2024-06-28   8.860000   TELB4

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   5.135384   TEND3
2010-01-05   5.089203   TEND3
2010-01-06   5.089203   TEND3
2010-01-07   5.061493   TEND3
2010-01-08   4.950658   TEND3
...               ...     ...
2024-06-24  10.769298   TEND3
2024-06-25  10.631104   TEND3
2024-06-26  10.463296   TEND3
2024-06-27  10.877879   TEND3
2024-06-28  10.611361   TEND3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04        NaN   TFCO4
2010-01-05        NaN   TFCO4
2010-01-06        NaN   TFCO4
2010-01-07        NaN   TFCO4
2010-01-08        NaN   TFCO4
...               ...     ...
2024-06-24  10.027888   TFCO4
2024-06-25  10.262458   TFCO4
2024-06-26  10.311329   TFCO4
2024-06-27  10.751147   TFCO4
2024-06-28  10.509810   TFCO4

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   8.309858   TGMA3
2010-01-05   8.282433   TGMA3
2010-01-06   8.331798   TGMA3
2010-01-07   8.189186   TGMA3
2010-01-08   8.194672   TGMA3
...               ...     ...
2024-06-24  22.019739   TGMA3
2024-06-25  22.165989   TGMA3
2024-06-26  21.809505   TGMA3
2024-06-27  22.339661   TGMA3
2024-06-28  22.339661   TGMA3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  0.000020   TIMS3
2010-01-05  0.000022   TIMS3
2010-01-06  0.000021   TIMS3
2010-01-07  0.000021   TIMS3
2010-01-08  0.000021   TIMS3
...              ...     ...
2024-06-24  4.895743   TIMS3
2024-06-25  4.905038   TIMS3
2024-06-26  4.905038   TIMS3
2024-06-27  4.951518   TIMS3
2024-06-28  4.920532   TIMS3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  30.569088   TKNO4
2010-01-05  30.569088   TKNO4
2010-01-06  30.569088   TKNO4
2010-01-07  30.569088   TKNO4
2010-01-08  30.569088   TKNO4
...               ...     ...
2024-06-24  60.998112   TKNO4
2024-06-25  60.998112   TKNO4
2024-06-26  60.998112   TKNO4
2024-06-27  60.998112   TKNO4
2024-06-28  60.998112   TKNO4

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   6.066864   TOTS3
2010-01-05   5.965326   TOTS3
2010-01-06   6.000864   TOTS3
2010-01-07   6.005943   TOTS3
2010-01-08   6.064325   TOTS3
...               ...     ...
2024-06-24  29.470869   TOTS3
2024-06-25  29.539181   TOTS3
2024-06-26  29.529419   TOTS3
2024-06-27  30.144209   TOTS3
2024-06-28  29.695316   TOTS3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  15.107265   TPIS3
2010-01-05  15.862627   TPIS3
2010-01-06  16.267288   TPIS3
2010-01-07  16.725903   TPIS3
2010-01-08  17.724066   TPIS3
...               ...     ...
2024-06-24   3.572137   TPIS3
2024-06-25   3.629752   TPIS3
2024-06-26   3.600945   TPIS3
2024-06-27   3.629752   TPIS3
2024-06-28   3.562535   TPIS3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04       NaN   TRAD3
2010-01-05       NaN   TRAD3
2010-01-06       NaN   TRAD3
2010-01-07       NaN   TRAD3
2010-01-08       NaN   TRAD3
...              ...     ...
2024-06-24  4.339999   TRAD3
2024-06-25  4.409999   TRAD3
2024-06-26  4.269999   TRAD3
2024-06-27  4.059999   TRAD3
2024-06-28  3.709999   TRAD3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  1.716186   TRIS3
2010-01-05  1.716186   TRIS3
2010-01-06  1.673012   TRIS3
2010-01-07  1.710789   TRIS3
2010-01-08  1.721583   TRIS3
...              ...     ...
2024-06-24  4.556148   TRIS3
2024-06-25  4.565720   TRIS3
2024-06-26  4.537004   TRIS3
2024-06-27  4.671009   TRIS3
2024-06-28  4.642293   TRIS3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   TRPL4
2010-01-05    NaN   TRPL4
2010-01-06    NaN   TRPL4
2010-01-07    NaN   TRPL4
2010-01-08    NaN   TRPL4
...           ...     ...
2024-06-24    NaN   TRPL4
2024-06-25    NaN   TRPL4
2024-06-26    NaN   TRPL4
2024-06-27    NaN   TRPL4
2024-06-28    NaN   TRPL4

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04       NaN   TTEN3
2010-01-05       NaN   TTEN3
2010-01-06       NaN   TTEN3
2010-01-07       NaN   TTEN3
2010-01-08       NaN   TTEN3
...              ...     ...
2024-06-24  9.900721   TTEN3
2024-06-25  9.624330   TTEN3
2024-06-26  9.614458   TTEN3
2024-06-27  9.940205   TTEN3
2024-06-28  9.752654   TTEN3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   4.140705   TUPY3
2010-01-05   4.217148   TUPY3
2010-01-06   4.083372   TUPY3
2010-01-07   4.140705   TUPY3
2010-01-08   4.080186   TUPY3
...               ...     ...
2024-06-24  22.093351   TUPY3
2024-06-25  22.065100   TUPY3
2024-06-26  22.046265   TUPY3
2024-06-27  22.272282   TUPY3
2024-06-28  22.253447   TUPY3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04       NaN   UCAS3
2010-01-05       NaN   UCAS3
2010-01-06       NaN   UCAS3
2010-01-07       NaN   UCAS3
2010-01-08       NaN   UCAS3
...              ...     ...
2024-06-24  1.981702   UCAS3
2024-06-25  1.981702   UCAS3
2024-06-26  1.908305   UCAS3
2024-06-27  1.981702   UCAS3
2024-06-28  1.972527   UCAS3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   2.108804   UGPA3
2010-01-05   2.108804   UGPA3
2010-01-06   2.108804   UGPA3
2010-01-07   2.108804   UGPA3
2010-01-08   2.108804   UGPA3
...               ...     ...
2024-06-24  21.223276   UGPA3
2024-06-25  20.877087   UGPA3
2024-06-26  20.694378   UGPA3
2024-06-27  21.213659   UGPA3
2024-06-28  20.771309   UGPA3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   2.326547   UNIP6
2010-01-05   2.510222   UNIP6
2010-01-06   2.469406   UNIP6
2010-01-07   2.387772   UNIP6
2010-01-08   2.367364   UNIP6
...               ...     ...
2024-06-24  45.904305   UNIP6
2024-06-25  45.790470   UNIP6
2024-06-26  45.515369   UNIP6
2024-06-27  46.577835   UNIP6
2024-06-28  46.283756   UNIP6

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  19.411186   USIM5
2010-01-05  19.468281   USIM5
2010-01-06  19.449249   USIM5
2010-01-07  19.631945   USIM5
2010-01-08  19.354097   USIM5
...               ...     ...
2024-06-24   7.690000   USIM5
2024-06-25   7.540000   USIM5
2024-06-26   7.790000   USIM5
2024-06-27   8.000000   USIM5
2024-06-28   7.910000   USIM5

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  23.717949   VALE3
2010-01-05  23.939051   VALE3
2010-01-06  24.445749   VALE3
2010-01-07  24.547081   VALE3
2010-01-08  24.786613   VALE3
...               ...     ...
2024-06-24  56.046478   VALE3
2024-06-25  55.816402   VALE3
2024-06-26  56.506630   VALE3
2024-06-27  56.653877   VALE3
2024-06-28  57.261280   VALE3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04       NaN   VAMO3
2010-01-05       NaN   VAMO3
2010-01-06       NaN   VAMO3
2010-01-07       NaN   VAMO3
2010-01-08       NaN   VAMO3
...              ...     ...
2024-06-24  7.467221   VAMO3
2024-06-25  7.219267   VAMO3
2024-06-26  7.352781   VAMO3
2024-06-27  7.381391   VAMO3
2024-06-28  7.219267   VAMO3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04        NaN   VBBR3
2010-01-05        NaN   VBBR3
2010-01-06        NaN   VBBR3
2010-01-07        NaN   VBBR3
2010-01-08        NaN   VBBR3
...               ...     ...
2024-06-24  19.723240   VBBR3
2024-06-25  19.151415   VBBR3
2024-06-26  19.488888   VBBR3
2024-06-27  20.004467   VBBR3
2024-06-28  19.592001   VBBR3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04       NaN   VITT3
2010-01-05       NaN   VITT3
2010-01-06       NaN   VITT3
2010-01-07       NaN   VITT3
2010-01-08       NaN   VITT3
...              ...     ...
2024-06-24  5.703758   VITT3
2024-06-25  5.635856   VITT3
2024-06-26  5.771660   VITT3
2024-06-27  5.897763   VITT3
2024-06-28  5.664957   VITT3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04        NaN   VIVA3
2010-01-05        NaN   VIVA3
2010-01-06        NaN   VIVA3
2010-01-07        NaN   VIVA3
2010-01-08        NaN   VIVA3
...               ...     ...
2024-06-24  20.551023   VIVA3
2024-06-25  20.260893   VIVA3
2024-06-26  19.796680   VIVA3
2024-06-27  20.502668   VIVA3
2024-06-28  20.251221   VIVA3

[3597 rows x 2 columns]

                   Close Empresa
Date
2010-01-04  21785.945312   VIVR3
2010-01-05  21660.376953   VIVR3
2010-01-06  23041.619141   VIVR3
2010-01-07  23229.970703   VIVR3
2010-01-08  23104.402344   VIVR3
...                  ...     ...
2024-06-24      2.330000   VIVR3
2024-06-25      2.260000   VIVR3
2024-06-26      2.300000   VIVR3
2024-06-27      2.340000   VIVR3
2024-06-28      2.320000   VIVR3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   8.921690   VIVT3
2010-01-05   8.888630   VIVT3
2010-01-06   8.737497   VIVT3
2010-01-07   8.737497   VIVT3
2010-01-08   8.730411   VIVT3
...               ...     ...
2024-06-24  21.212149   VIVT3
2024-06-25  21.277836   VIVT3
2024-06-26  21.667265   VIVT3
2024-06-27  21.512430   VIVT3
2024-06-28  21.273144   VIVT3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   9.031358   VLID3
2010-01-05   9.021999   VLID3
2010-01-06   9.054757   VLID3
2010-01-07   9.078152   VLID3
2010-01-08   9.265330   VLID3
...               ...     ...
2024-06-24  14.681923   VLID3
2024-06-25  14.378029   VLID3
2024-06-26  14.387525   VLID3
2024-06-27  14.558466   VLID3
2024-06-28  14.454002   VLID3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   VSPT3
2010-01-05    NaN   VSPT3
2010-01-06    NaN   VSPT3
2010-01-07    NaN   VSPT3
2010-01-08    NaN   VSPT3
...           ...     ...
2024-06-24    1.5   VSPT3
2024-06-25    1.5   VSPT3
2024-06-26    1.5   VSPT3
2024-06-27    1.5   VSPT3
2024-06-28    1.5   VSPT3

[3597 rows x 2 columns]

                 Close Empresa
Date
2010-01-04  120.015137   VSTE3
2010-01-05  117.826347   VSTE3
2010-01-06  117.096779   VSTE3
2010-01-07  116.732040   VSTE3
2010-01-08  116.549606   VSTE3
...                ...     ...
2024-06-24   17.086391   VSTE3
2024-06-25   17.196369   VSTE3
2024-06-26   17.086391   VSTE3
2024-06-27   17.096390   VSTE3
2024-06-28   17.096390   VSTE3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04  17.140339   VULC3
2010-01-05  17.346025   VULC3
2010-01-06  17.140339   VULC3
2010-01-07  17.620274   VULC3
2010-01-08  17.620274   VULC3
...               ...     ...
2024-06-24  13.550424   VULC3
2024-06-25  13.458743   VULC3
2024-06-26  13.385399   VULC3
2024-06-27  13.669609   VULC3
2024-06-28  13.559592   VULC3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   VVEO3
2010-01-05    NaN   VVEO3
2010-01-06    NaN   VVEO3
2010-01-07    NaN   VVEO3
2010-01-08    NaN   VVEO3
...           ...     ...
2024-06-24   2.07   VVEO3
2024-06-25   2.11   VVEO3
2024-06-26   2.12   VVEO3
2024-06-27   2.32   VVEO3
2024-06-28   2.24   VVEO3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   2.003207   WEGE3
2010-01-05   1.998836   WEGE3
2010-01-06   2.009764   WEGE3
2010-01-07   2.043643   WEGE3
2010-01-08   2.117956   WEGE3
...               ...     ...
2024-06-24  40.134163   WEGE3
2024-06-25  40.821556   WEGE3
2024-06-26  41.194721   WEGE3
2024-06-27  40.949219   WEGE3
2024-06-28  41.430393   WEGE3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   WEST3
2010-01-05    NaN   WEST3
2010-01-06    NaN   WEST3
2010-01-07    NaN   WEST3
2010-01-08    NaN   WEST3
...           ...     ...
2024-06-24    9.0   WEST3
2024-06-25    8.9   WEST3
2024-06-26    8.6   WEST3
2024-06-27    8.7   WEST3
2024-06-28    8.7   WEST3

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04  1.004303   WHRL4
2010-01-05  0.995743   WHRL4
2010-01-06  0.981478   WHRL4
2010-01-07  0.978625   WHRL4
2010-01-08  0.984331   WHRL4
...              ...     ...
2024-06-24  3.887461   WHRL4
2024-06-25  3.852751   WHRL4
2024-06-26  3.835397   WHRL4
2024-06-27  3.844074   WHRL4
2024-06-28  3.948202   WHRL4

[3597 rows x 2 columns]

               Close Empresa
Date
2010-01-04       NaN   WIZC3
2010-01-05       NaN   WIZC3
2010-01-06       NaN   WIZC3
2010-01-07       NaN   WIZC3
2010-01-08       NaN   WIZC3
...              ...     ...
2024-06-24  5.589578   WIZC3
2024-06-25  5.503290   WIZC3
2024-06-26  5.464939   WIZC3
2024-06-27  5.608753   WIZC3
2024-06-28  5.474527   WIZC3

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   4.982957   WLMM4
2010-01-05   4.982957   WLMM4
2010-01-06   5.172183   WLMM4
2010-01-07   5.191106   WLMM4
2010-01-08   5.361410   WLMM4
...               ...     ...
2024-06-24  29.649946   WLMM4
2024-06-25  29.126713   WLMM4
2024-06-26  29.834047   WLMM4
2024-06-27  30.037527   WLMM4
2024-06-28  30.425108   WLMM4

[3597 rows x 2 columns]

                Close Empresa
Date
2010-01-04   5.535982   YDUQ3
2010-01-05   5.602295   YDUQ3
2010-01-06   5.693761   YDUQ3
2010-01-07   5.602295   YDUQ3
2010-01-08   5.602295   YDUQ3
...               ...     ...
2024-06-24  11.110000   YDUQ3
2024-06-25  10.790000   YDUQ3
2024-06-26  10.650000   YDUQ3
2024-06-27  11.040000   YDUQ3
2024-06-28  10.410000   YDUQ3

[3597 rows x 2 columns]

            Close Empresa
Date
2010-01-04    NaN   ZAMP3
2010-01-05    NaN   ZAMP3
2010-01-06    NaN   ZAMP3
2010-01-07    NaN   ZAMP3
2010-01-08    NaN   ZAMP3
...           ...     ...
2024-06-24   3.82   ZAMP3
2024-06-25   3.62   ZAMP3
2024-06-26   3.57   ZAMP3
2024-06-27   3.78   ZAMP3
2024-06-28   3.74   ZAMP3

[3597 rows x 2 columns]

### Cotacão histórica do IBOV

In [44]:
cot_ibov = r'C:\Users\tiakk\OneDrive\Documentos\Balanços\cotações\Cotação_IBOV'
inicio = "2010-01-02"
fim = "2024-07-01"

ibov = '^BVSP'

cotacaoibov_df=yf.download(tickers=ibov, start=inicio, end=fim)["Close"]
    

display(cotacaoibov_df)

dfi = cotacaoibov_df.to_excel(f'{cot_ibov}/cotacao_ibov.xlsx')

C:\Users\tiakk\AppData\Local\Temp\ipykernel_96328\3850601712.py:7: FutureWarning: YF.download() has changed argument auto_adjust default to True
  cotacaoibov_df=yf.download(tickers=ibov, start=inicio, end=fim)["Close"]
[*********************100%***********************]  1 of 1 completed

Ticker         ^BVSP
Date
2010-01-04   70045.0
2010-01-05   70240.0
2010-01-06   70729.0
2010-01-07   70451.0
2010-01-08   70263.0
...              ...
2024-06-24  122637.0
2024-06-25  122331.0
2024-06-26  122641.0
2024-06-27  124308.0
2024-06-28  123907.0

[3588 rows x 1 columns]

In [45]:
# Remover ".SA" dos nomes das empresas nas colunas da tabela

cotacaoibov_df = pd.read_excel(f'{cot_ibov}/cotacao_ibov.xlsx')
df = cotacaoibov_df


for empresa in cotacaoibov_df.columns:
    if empresa == "Date":
        pass
    
    else:
    
        novonome = "IBOV"

        #print(novonome)
        cotacaoibov_df.rename(columns={f'{empresa}': f'{novonome}'}, inplace=True)

cotacaoibov_df = cotacaoibov_df.set_index('Date') 

display(cotacaoibov_df)

              IBOV
Date
2010-01-04   70045
2010-01-05   70240
2010-01-06   70729
2010-01-07   70451
2010-01-08   70263
...            ...
2024-06-24  122637
2024-06-25  122331
2024-06-26  122641
2024-06-27  124308
2024-06-28  123907

[3588 rows x 1 columns]

In [47]:
display(cotacaoibov_df.index)

DatetimeIndex(['2010-01-04', '2010-01-05', '2010-01-06', '2010-01-07',
               '2010-01-08', '2010-01-11', '2010-01-12', '2010-01-13',
               '2010-01-14', '2010-01-15',
               ...
               '2024-06-17', '2024-06-18', '2024-06-19', '2024-06-20',
               '2024-06-21', '2024-06-24', '2024-06-25', '2024-06-26',
               '2024-06-27', '2024-06-28'],
              dtype='datetime64[ns]', name='Date', length=3588, freq=None)